/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Mon Nov  7 14:13:00 2016
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */

#define u_width 10
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
#ifndef MATLAB_MEX_FILE
#define RPIT_SOCKET_API
#include "rpit_socket_client.c"
#endif
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void rpi_sfun_iosocket_Outputs_wrapper(const real_T *u0,
                          real_T *y0  , 
                          const real_T  *rpi_Ts, const int_T  p_width0, 
                          const uint8_T  *rpi_ip1, const int_T  p_width1, 
                          const uint8_T  *rpi_ip2, const int_T  p_width2, 
                          const uint8_T  *rpi_ip3, const int_T  p_width3, 
                          const uint8_T  *rpi_ip4,  const int_T p_width4)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
#ifdef MATLAB_MEX_FILE
  y0[0] = 0.0;
  y0[1] = 0.0;
  y0[2] = 0.0;
  y0[3] = 0.0;
  y0[4] = 0.0;
  y0[5] = 0.0;
  y0[6] = 0.0;
  y0[7] = 0.0;
  y0[8] = 0.0;
  y0[9] = 0.0;
#else
  (void)p_width0;
  (void)p_width1;
  (void)p_width2;
  (void)p_width3;
  (void)p_width4;
  
  if ( *rpi_Ts < 0.001 )	{
    fprintf( stderr, "** Max sampling rate = 1000Hz **\n" );
    y0[0] = 0.0;
    y0[1] = 0.0;
    y0[2] = 0.0;
    y0[3] = 0.0;
    y0[4] = 0.0;
    y0[5] = 0.0;
    y0[6] = 0.0;
    y0[7] = 0.0;
    y0[8] = 0.0;
    y0[9] = 0.0;
    return;
  }
  
  /* Send control signals */
  
  rpit_socket_client_write( *rpi_ip1, *rpi_ip2, *rpi_ip3, *rpi_ip4, u0 );
  
  /* Read measurements */
  
  rpit_socket_client_read( *rpi_ip1, *rpi_ip2, *rpi_ip3, *rpi_ip4, y0 );
  
#endif
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
