/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Fri May 25 13:43:50 2018
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
#ifndef MATLAB_MEX_FILE
#include "rgpio.c"
#endif
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void rpi_sfun_rgpio_Outputs_wrapper(const real_T *pin11,
                          const real_T *pin13,
                          const real_T *pin15,
                          const real_T *pin29,
                          const real_T *pin31,
                          const real_T *pin37,
                          real_T *pin12,
                          real_T *pin16,
                          real_T *pin18,
                          real_T *pin22,
                          real_T *pin36, 
                           const real_T  *rpi_Ts, const int_T p_width0)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
#ifdef MATLAB_MEX_FILE

  pin12[0] = 0.0;
  pin16[0] = 0.0;
  pin18[0] = 0.0;
  pin22[0] = 0.0;
  pin36[0] = 0.0;
  
#else
  
  if ( p_width0 > 1 )	{
    fprintf( stderr, "** Multiple rates not allowed in this block **\n" );
    pin12[0] = 0.0;
    pin16[0] = 0.0;
    pin18[0] = 0.0;
    pin22[0] = 0.0;
    pin36[0] = 0.0;
    return;
  }

  if ( *rpi_Ts < 0.001 )	{
    fprintf( stderr, "** Max sampling rate = 1000Hz **\n" );
    pin12[0] = 0.0;
    pin16[0] = 0.0;
    pin18[0] = 0.0;
    pin22[0] = 0.0;
    pin36[0] = 0.0;
    return;
  }
  
  rgpio_write_gpio( rgpio_output_port[0], ( *pin11 == RGPIO_LOW ? RGPIO_LOW : RGPIO_HIGH  ) );
  rgpio_write_gpio( rgpio_output_port[1], ( *pin13 == RGPIO_LOW ? RGPIO_LOW : RGPIO_HIGH  ) );
  rgpio_write_gpio( rgpio_output_port[2], ( *pin15 == RGPIO_LOW ? RGPIO_LOW : RGPIO_HIGH  ) );
  rgpio_write_gpio( rgpio_output_port[3], ( *pin29 == RGPIO_LOW ? RGPIO_LOW : RGPIO_HIGH  ) );
  rgpio_write_gpio( rgpio_output_port[4], ( *pin31 == RGPIO_LOW ? RGPIO_LOW : RGPIO_HIGH  ) );
  rgpio_write_gpio( rgpio_output_port[5], ( *pin37 == RGPIO_LOW ? RGPIO_LOW : RGPIO_HIGH  ) );
  
  pin12[0] = (real_T)rgpio_read_gpio( rgpio_input_port[0] );
  pin16[0] = (real_T)rgpio_read_gpio( rgpio_input_port[1] );
  pin18[0] = (real_T)rgpio_read_gpio( rgpio_input_port[2] );
  pin22[0] = (real_T)rgpio_read_gpio( rgpio_input_port[3] );
  pin36[0] = (real_T)rgpio_read_gpio( rgpio_input_port[4] );
  
#endif
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
