/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Mon Oct 17 17:05:03 2016
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */

#define RPITJS_NB_AXES    8
#define RPITJS_NB_BUTTONS 11

#ifndef MATLAB_MEX_FILE

#define RPITJS_API
#include "rpit_js.c"

#endif

/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void rpi_sfun_js_Outputs_wrapper(real_T *Axes,
                          real_T *Buttons  , 
                          const real_T  *rpi_ID, const int_T  p_width0, 
                          const real_T  *rpi_Ts,  const int_T p_width1)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
  
  int i;
  (void)p_width0;
  (void)p_width1;

  #ifdef MATLAB_MEX_FILE

  for ( i = 0; i < RPITJS_NB_AXES; i++ )
    Axes[i] = 0.0;
  for ( i = 0; i < RPITJS_NB_BUTTONS; i++ )
    Buttons[i] = 0.0;

  #else
  
  /* Consistency check */
          
  if ( ( *rpi_ID >= RPITJS_MAX_JS ) || ( *rpi_ID < 0 ) || ( *rpi_Ts < 0.001 ) )  {
    for ( i = 0; i < RPITJS_NB_AXES; i++ )
      Axes[i] = 0.0;
    for ( i = 0; i < RPITJS_NB_BUTTONS; i++ )
      Buttons[i] = 0.0;
    return;
  }
  
  /* Read jostick values */
  
  if ( rpitjs_read( (int)*rpi_ID ) < 0 )  {
    for ( i = 0; i < RPITJS_NB_AXES; i++ )
      Axes[i] = 0.0;
    for ( i = 0; i < RPITJS_NB_BUTTONS; i++ )
      Buttons[i] = 0.0;
  }
  else {
    for ( i = 0; i < RPITJS_NB_AXES; i++ )
      if ( i < rpitjs_struct[(int)*rpi_ID].nb_axes )
        Axes[i] = rpitjs_struct[(int)*rpi_ID].axis_values[i];
      else
        Axes[i] = 0.0;
    for ( i = 0; i < RPITJS_NB_BUTTONS; i++ )
      if ( i < rpitjs_struct[(int)*rpi_ID].nb_buttons )
        Buttons[i] = rpitjs_struct[(int)*rpi_ID].button_values[i];
      else
        Buttons[i] = 0.0;
  }
  
  #endif
          
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
