/*
 * File: rpi_sfun_dxl.c
 *
 *
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is an S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_defines_Changes_BEGIN
  *        #define NAME 'replacement text' 
  *        %%% SFUNWIZ_defines_Changes_END
  *
  *   DO NOT change NAME--Change the 'replacement text' only.
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *  -------------------------------------------------------------------------
  * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
  *  ------------------------------------------------------------------------- 
 * Created: Wed Aug 31 16:16:04 2016
 * 
 *
 */

#define S_FUNCTION_LEVEL 2
#define S_FUNCTION_NAME rpi_sfun_dxl
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS          10
/* Input Port  0 */
#define IN_PORT_0_NAME      u1
#define INPUT_0_WIDTH       1
#define INPUT_DIMS_0_COL    1
#define INPUT_0_DTYPE       real_T
#define INPUT_0_COMPLEX     COMPLEX_NO
#define IN_0_FRAME_BASED    FRAME_NO
#define IN_0_BUS_BASED      0
#define IN_0_BUS_NAME       
#define IN_0_DIMS           1-D
#define INPUT_0_FEEDTHROUGH 1
#define IN_0_ISSIGNED        0
#define IN_0_WORDLENGTH      8
#define IN_0_FIXPOINTSCALING 1
#define IN_0_FRACTIONLENGTH  9
#define IN_0_BIAS            0
#define IN_0_SLOPE           0.125
/* Input Port  1 */
#define IN_PORT_1_NAME      u2
#define INPUT_1_WIDTH       1
#define INPUT_DIMS_1_COL    1
#define INPUT_1_DTYPE       real_T
#define INPUT_1_COMPLEX     COMPLEX_NO
#define IN_1_FRAME_BASED    FRAME_NO
#define IN_1_BUS_BASED      0
#define IN_1_BUS_NAME       
#define IN_1_DIMS           1-D
#define INPUT_1_FEEDTHROUGH 1
#define IN_1_ISSIGNED        0
#define IN_1_WORDLENGTH      8
#define IN_1_FIXPOINTSCALING 1
#define IN_1_FRACTIONLENGTH  9
#define IN_1_BIAS            0
#define IN_1_SLOPE           0.125
/* Input Port  2 */
#define IN_PORT_2_NAME      u3
#define INPUT_2_WIDTH       1
#define INPUT_DIMS_2_COL    1
#define INPUT_2_DTYPE       real_T
#define INPUT_2_COMPLEX     COMPLEX_NO
#define IN_2_FRAME_BASED    FRAME_NO
#define IN_2_BUS_BASED      0
#define IN_2_BUS_NAME       
#define IN_2_DIMS           1-D
#define INPUT_2_FEEDTHROUGH 1
#define IN_2_ISSIGNED        0
#define IN_2_WORDLENGTH      8
#define IN_2_FIXPOINTSCALING 1
#define IN_2_FRACTIONLENGTH  9
#define IN_2_BIAS            0
#define IN_2_SLOPE           0.125
/* Input Port  3 */
#define IN_PORT_3_NAME      u4
#define INPUT_3_WIDTH       1
#define INPUT_DIMS_3_COL    1
#define INPUT_3_DTYPE       real_T
#define INPUT_3_COMPLEX     COMPLEX_NO
#define IN_3_FRAME_BASED    FRAME_NO
#define IN_3_BUS_BASED      0
#define IN_3_BUS_NAME       
#define IN_3_DIMS           1-D
#define INPUT_3_FEEDTHROUGH 1
#define IN_3_ISSIGNED        0
#define IN_3_WORDLENGTH      8
#define IN_3_FIXPOINTSCALING 1
#define IN_3_FRACTIONLENGTH  9
#define IN_3_BIAS            0
#define IN_3_SLOPE           0.125
/* Input Port  4 */
#define IN_PORT_4_NAME      u5
#define INPUT_4_WIDTH       1
#define INPUT_DIMS_4_COL    1
#define INPUT_4_DTYPE       real_T
#define INPUT_4_COMPLEX     COMPLEX_NO
#define IN_4_FRAME_BASED    FRAME_NO
#define IN_4_BUS_BASED      0
#define IN_4_BUS_NAME       
#define IN_4_DIMS           1-D
#define INPUT_4_FEEDTHROUGH 1
#define IN_4_ISSIGNED        0
#define IN_4_WORDLENGTH      8
#define IN_4_FIXPOINTSCALING 1
#define IN_4_FRACTIONLENGTH  9
#define IN_4_BIAS            0
#define IN_4_SLOPE           0.125
/* Input Port  5 */
#define IN_PORT_5_NAME      u6
#define INPUT_5_WIDTH       1
#define INPUT_DIMS_5_COL    1
#define INPUT_5_DTYPE       real_T
#define INPUT_5_COMPLEX     COMPLEX_NO
#define IN_5_FRAME_BASED    FRAME_NO
#define IN_5_BUS_BASED      0
#define IN_5_BUS_NAME       
#define IN_5_DIMS           1-D
#define INPUT_5_FEEDTHROUGH 1
#define IN_5_ISSIGNED        0
#define IN_5_WORDLENGTH      8
#define IN_5_FIXPOINTSCALING 1
#define IN_5_FRACTIONLENGTH  9
#define IN_5_BIAS            0
#define IN_5_SLOPE           0.125
/* Input Port  6 */
#define IN_PORT_6_NAME      u7
#define INPUT_6_WIDTH       1
#define INPUT_DIMS_6_COL    1
#define INPUT_6_DTYPE       real_T
#define INPUT_6_COMPLEX     COMPLEX_NO
#define IN_6_FRAME_BASED    FRAME_NO
#define IN_6_BUS_BASED      0
#define IN_6_BUS_NAME       
#define IN_6_DIMS           1-D
#define INPUT_6_FEEDTHROUGH 1
#define IN_6_ISSIGNED        0
#define IN_6_WORDLENGTH      8
#define IN_6_FIXPOINTSCALING 1
#define IN_6_FRACTIONLENGTH  9
#define IN_6_BIAS            0
#define IN_6_SLOPE           0.125
/* Input Port  7 */
#define IN_PORT_7_NAME      u8
#define INPUT_7_WIDTH       1
#define INPUT_DIMS_7_COL    1
#define INPUT_7_DTYPE       real_T
#define INPUT_7_COMPLEX     COMPLEX_NO
#define IN_7_FRAME_BASED    FRAME_NO
#define IN_7_BUS_BASED      0
#define IN_7_BUS_NAME       
#define IN_7_DIMS           1-D
#define INPUT_7_FEEDTHROUGH 1
#define IN_7_ISSIGNED        0
#define IN_7_WORDLENGTH      8
#define IN_7_FIXPOINTSCALING 1
#define IN_7_FRACTIONLENGTH  9
#define IN_7_BIAS            0
#define IN_7_SLOPE           0.125
/* Input Port  8 */
#define IN_PORT_8_NAME      u9
#define INPUT_8_WIDTH       1
#define INPUT_DIMS_8_COL    1
#define INPUT_8_DTYPE       real_T
#define INPUT_8_COMPLEX     COMPLEX_NO
#define IN_8_FRAME_BASED    FRAME_NO
#define IN_8_BUS_BASED      0
#define IN_8_BUS_NAME       
#define IN_8_DIMS           1-D
#define INPUT_8_FEEDTHROUGH 1
#define IN_8_ISSIGNED        0
#define IN_8_WORDLENGTH      8
#define IN_8_FIXPOINTSCALING 1
#define IN_8_FRACTIONLENGTH  9
#define IN_8_BIAS            0
#define IN_8_SLOPE           0.125
/* Input Port  9 */
#define IN_PORT_9_NAME      u10
#define INPUT_9_WIDTH       1
#define INPUT_DIMS_9_COL    1
#define INPUT_9_DTYPE       real_T
#define INPUT_9_COMPLEX     COMPLEX_NO
#define IN_9_FRAME_BASED    FRAME_NO
#define IN_9_BUS_BASED      0
#define IN_9_BUS_NAME       
#define IN_9_DIMS           1-D
#define INPUT_9_FEEDTHROUGH 1
#define IN_9_ISSIGNED        0
#define IN_9_WORDLENGTH      8
#define IN_9_FIXPOINTSCALING 1
#define IN_9_FRACTIONLENGTH  9
#define IN_9_BIAS            0
#define IN_9_SLOPE           0.125

#define NUM_OUTPUTS          10
/* Output Port  0 */
#define OUT_PORT_0_NAME      y1
#define OUTPUT_0_WIDTH       1
#define OUTPUT_DIMS_0_COL    1
#define OUTPUT_0_DTYPE       real_T
#define OUTPUT_0_COMPLEX     COMPLEX_NO
#define OUT_0_FRAME_BASED    FRAME_NO
#define OUT_0_BUS_BASED      0
#define OUT_0_BUS_NAME       
#define OUT_0_DIMS           1-D
#define OUT_0_ISSIGNED        1
#define OUT_0_WORDLENGTH      8
#define OUT_0_FIXPOINTSCALING 1
#define OUT_0_FRACTIONLENGTH  3
#define OUT_0_BIAS            0
#define OUT_0_SLOPE           0.125
/* Output Port  1 */
#define OUT_PORT_1_NAME      y2
#define OUTPUT_1_WIDTH       1
#define OUTPUT_DIMS_1_COL    1
#define OUTPUT_1_DTYPE       real_T
#define OUTPUT_1_COMPLEX     COMPLEX_NO
#define OUT_1_FRAME_BASED    FRAME_NO
#define OUT_1_BUS_BASED      0
#define OUT_1_BUS_NAME       
#define OUT_1_DIMS           1-D
#define OUT_1_ISSIGNED        1
#define OUT_1_WORDLENGTH      8
#define OUT_1_FIXPOINTSCALING 1
#define OUT_1_FRACTIONLENGTH  3
#define OUT_1_BIAS            0
#define OUT_1_SLOPE           0.125
/* Output Port  2 */
#define OUT_PORT_2_NAME      y3
#define OUTPUT_2_WIDTH       1
#define OUTPUT_DIMS_2_COL    1
#define OUTPUT_2_DTYPE       real_T
#define OUTPUT_2_COMPLEX     COMPLEX_NO
#define OUT_2_FRAME_BASED    FRAME_NO
#define OUT_2_BUS_BASED      0
#define OUT_2_BUS_NAME       
#define OUT_2_DIMS           1-D
#define OUT_2_ISSIGNED        1
#define OUT_2_WORDLENGTH      8
#define OUT_2_FIXPOINTSCALING 1
#define OUT_2_FRACTIONLENGTH  3
#define OUT_2_BIAS            0
#define OUT_2_SLOPE           0.125
/* Output Port  3 */
#define OUT_PORT_3_NAME      y4
#define OUTPUT_3_WIDTH       1
#define OUTPUT_DIMS_3_COL    1
#define OUTPUT_3_DTYPE       real_T
#define OUTPUT_3_COMPLEX     COMPLEX_NO
#define OUT_3_FRAME_BASED    FRAME_NO
#define OUT_3_BUS_BASED      0
#define OUT_3_BUS_NAME       
#define OUT_3_DIMS           1-D
#define OUT_3_ISSIGNED        1
#define OUT_3_WORDLENGTH      8
#define OUT_3_FIXPOINTSCALING 1
#define OUT_3_FRACTIONLENGTH  3
#define OUT_3_BIAS            0
#define OUT_3_SLOPE           0.125
/* Output Port  4 */
#define OUT_PORT_4_NAME      y5
#define OUTPUT_4_WIDTH       1
#define OUTPUT_DIMS_4_COL    1
#define OUTPUT_4_DTYPE       real_T
#define OUTPUT_4_COMPLEX     COMPLEX_NO
#define OUT_4_FRAME_BASED    FRAME_NO
#define OUT_4_BUS_BASED      0
#define OUT_4_BUS_NAME       
#define OUT_4_DIMS           1-D
#define OUT_4_ISSIGNED        1
#define OUT_4_WORDLENGTH      8
#define OUT_4_FIXPOINTSCALING 1
#define OUT_4_FRACTIONLENGTH  3
#define OUT_4_BIAS            0
#define OUT_4_SLOPE           0.125
/* Output Port  5 */
#define OUT_PORT_5_NAME      y6
#define OUTPUT_5_WIDTH       1
#define OUTPUT_DIMS_5_COL    1
#define OUTPUT_5_DTYPE       real_T
#define OUTPUT_5_COMPLEX     COMPLEX_NO
#define OUT_5_FRAME_BASED    FRAME_NO
#define OUT_5_BUS_BASED      0
#define OUT_5_BUS_NAME       
#define OUT_5_DIMS           1-D
#define OUT_5_ISSIGNED        1
#define OUT_5_WORDLENGTH      8
#define OUT_5_FIXPOINTSCALING 1
#define OUT_5_FRACTIONLENGTH  3
#define OUT_5_BIAS            0
#define OUT_5_SLOPE           0.125
/* Output Port  6 */
#define OUT_PORT_6_NAME      y7
#define OUTPUT_6_WIDTH       1
#define OUTPUT_DIMS_6_COL    1
#define OUTPUT_6_DTYPE       real_T
#define OUTPUT_6_COMPLEX     COMPLEX_NO
#define OUT_6_FRAME_BASED    FRAME_NO
#define OUT_6_BUS_BASED      0
#define OUT_6_BUS_NAME       
#define OUT_6_DIMS           1-D
#define OUT_6_ISSIGNED        1
#define OUT_6_WORDLENGTH      8
#define OUT_6_FIXPOINTSCALING 1
#define OUT_6_FRACTIONLENGTH  3
#define OUT_6_BIAS            0
#define OUT_6_SLOPE           0.125
/* Output Port  7 */
#define OUT_PORT_7_NAME      y8
#define OUTPUT_7_WIDTH       1
#define OUTPUT_DIMS_7_COL    1
#define OUTPUT_7_DTYPE       real_T
#define OUTPUT_7_COMPLEX     COMPLEX_NO
#define OUT_7_FRAME_BASED    FRAME_NO
#define OUT_7_BUS_BASED      0
#define OUT_7_BUS_NAME       
#define OUT_7_DIMS           1-D
#define OUT_7_ISSIGNED        1
#define OUT_7_WORDLENGTH      8
#define OUT_7_FIXPOINTSCALING 1
#define OUT_7_FRACTIONLENGTH  3
#define OUT_7_BIAS            0
#define OUT_7_SLOPE           0.125
/* Output Port  8 */
#define OUT_PORT_8_NAME      y9
#define OUTPUT_8_WIDTH       1
#define OUTPUT_DIMS_8_COL    1
#define OUTPUT_8_DTYPE       real_T
#define OUTPUT_8_COMPLEX     COMPLEX_NO
#define OUT_8_FRAME_BASED    FRAME_NO
#define OUT_8_BUS_BASED      0
#define OUT_8_BUS_NAME       
#define OUT_8_DIMS           1-D
#define OUT_8_ISSIGNED        1
#define OUT_8_WORDLENGTH      8
#define OUT_8_FIXPOINTSCALING 1
#define OUT_8_FRACTIONLENGTH  3
#define OUT_8_BIAS            0
#define OUT_8_SLOPE           0.125
/* Output Port  9 */
#define OUT_PORT_9_NAME      y10
#define OUTPUT_9_WIDTH       1
#define OUTPUT_DIMS_9_COL    1
#define OUTPUT_9_DTYPE       real_T
#define OUTPUT_9_COMPLEX     COMPLEX_NO
#define OUT_9_FRAME_BASED    FRAME_NO
#define OUT_9_BUS_BASED      0
#define OUT_9_BUS_NAME       
#define OUT_9_DIMS           1-D
#define OUT_9_ISSIGNED        1
#define OUT_9_WORDLENGTH      8
#define OUT_9_FIXPOINTSCALING 1
#define OUT_9_FRACTIONLENGTH  3
#define OUT_9_BIAS            0
#define OUT_9_SLOPE           0.125

#define NPARAMS              41
/* Parameter  1 */
#define PARAMETER_0_NAME      rpi_Ts
#define PARAMETER_0_DTYPE     real_T
#define PARAMETER_0_COMPLEX   COMPLEX_NO
/* Parameter  2 */
#define PARAMETER_1_NAME      rpi_portname
#define PARAMETER_1_DTYPE     uint8_T
#define PARAMETER_1_COMPLEX   COMPLEX_NO
/* Parameter  3 */
#define PARAMETER_2_NAME      rpi_baudrate
#define PARAMETER_2_DTYPE     uint32_T
#define PARAMETER_2_COMPLEX   COMPLEX_NO
/* Parameter  4 */
#define PARAMETER_3_NAME      rpi_startid
#define PARAMETER_3_DTYPE     uint8_T
#define PARAMETER_3_COMPLEX   COMPLEX_NO
/* Parameter  5 */
#define PARAMETER_4_NAME      rpi_nbid
#define PARAMETER_4_DTYPE     uint8_T
#define PARAMETER_4_COMPLEX   COMPLEX_NO
/* Parameter  6 */
#define PARAMETER_5_NAME      rpi_proto
#define PARAMETER_5_DTYPE     uint8_T
#define PARAMETER_5_COMPLEX   COMPLEX_NO
/* Parameter  7 */
#define PARAMETER_6_NAME      rpi_write_addr
#define PARAMETER_6_DTYPE     uint16_T
#define PARAMETER_6_COMPLEX   COMPLEX_NO
/* Parameter  8 */
#define PARAMETER_7_NAME      rpi_write_length
#define PARAMETER_7_DTYPE     uint8_T
#define PARAMETER_7_COMPLEX   COMPLEX_NO
/* Parameter  9 */
#define PARAMETER_8_NAME      rpi_read_addr
#define PARAMETER_8_DTYPE     uint16_T
#define PARAMETER_8_COMPLEX   COMPLEX_NO
/* Parameter  10 */
#define PARAMETER_9_NAME      rpi_read_length
#define PARAMETER_9_DTYPE     uint8_T
#define PARAMETER_9_COMPLEX   COMPLEX_NO
/* Parameter  11 */
#define PARAMETER_10_NAME      rpi_read_sign
#define PARAMETER_10_DTYPE     uint8_T
#define PARAMETER_10_COMPLEX   COMPLEX_NO
/* Parameter  12 */
#define PARAMETER_11_NAME      rpi_init1_addr
#define PARAMETER_11_DTYPE     uint16_T
#define PARAMETER_11_COMPLEX   COMPLEX_NO
/* Parameter  13 */
#define PARAMETER_12_NAME      rpi_init1_length
#define PARAMETER_12_DTYPE     uint8_T
#define PARAMETER_12_COMPLEX   COMPLEX_NO
/* Parameter  14 */
#define PARAMETER_13_NAME      rpi_init1_data
#define PARAMETER_13_DTYPE     real_T
#define PARAMETER_13_COMPLEX   COMPLEX_NO
/* Parameter  15 */
#define PARAMETER_14_NAME      rpi_init2_addr
#define PARAMETER_14_DTYPE     uint16_T
#define PARAMETER_14_COMPLEX   COMPLEX_NO
/* Parameter  16 */
#define PARAMETER_15_NAME      rpi_init2_length
#define PARAMETER_15_DTYPE     uint8_T
#define PARAMETER_15_COMPLEX   COMPLEX_NO
/* Parameter  17 */
#define PARAMETER_16_NAME      rpi_init2_data
#define PARAMETER_16_DTYPE     real_T
#define PARAMETER_16_COMPLEX   COMPLEX_NO
/* Parameter  18 */
#define PARAMETER_17_NAME      rpi_init3_addr
#define PARAMETER_17_DTYPE     uint16_T
#define PARAMETER_17_COMPLEX   COMPLEX_NO
/* Parameter  19 */
#define PARAMETER_18_NAME      rpi_init3_length
#define PARAMETER_18_DTYPE     uint8_T
#define PARAMETER_18_COMPLEX   COMPLEX_NO
/* Parameter  20 */
#define PARAMETER_19_NAME      rpi_init3_data
#define PARAMETER_19_DTYPE     real_T
#define PARAMETER_19_COMPLEX   COMPLEX_NO
/* Parameter  21 */
#define PARAMETER_20_NAME      rpi_init4_addr
#define PARAMETER_20_DTYPE     uint16_T
#define PARAMETER_20_COMPLEX   COMPLEX_NO
/* Parameter  22 */
#define PARAMETER_21_NAME      rpi_init4_length
#define PARAMETER_21_DTYPE     uint8_T
#define PARAMETER_21_COMPLEX   COMPLEX_NO
/* Parameter  23 */
#define PARAMETER_22_NAME      rpi_init4_data
#define PARAMETER_22_DTYPE     real_T
#define PARAMETER_22_COMPLEX   COMPLEX_NO
/* Parameter  24 */
#define PARAMETER_23_NAME      rpi_init5_addr
#define PARAMETER_23_DTYPE     uint16_T
#define PARAMETER_23_COMPLEX   COMPLEX_NO
/* Parameter  25 */
#define PARAMETER_24_NAME      rpi_init5_length
#define PARAMETER_24_DTYPE     uint8_T
#define PARAMETER_24_COMPLEX   COMPLEX_NO
/* Parameter  26 */
#define PARAMETER_25_NAME      rpi_init5_data
#define PARAMETER_25_DTYPE     real_T
#define PARAMETER_25_COMPLEX   COMPLEX_NO
/* Parameter  27 */
#define PARAMETER_26_NAME      rpi_init6_addr
#define PARAMETER_26_DTYPE     uint16_T
#define PARAMETER_26_COMPLEX   COMPLEX_NO
/* Parameter  28 */
#define PARAMETER_27_NAME      rpi_init6_length
#define PARAMETER_27_DTYPE     uint8_T
#define PARAMETER_27_COMPLEX   COMPLEX_NO
/* Parameter  29 */
#define PARAMETER_28_NAME      rpi_init6_data
#define PARAMETER_28_DTYPE     real_T
#define PARAMETER_28_COMPLEX   COMPLEX_NO
/* Parameter  30 */
#define PARAMETER_29_NAME      rpi_init7_addr
#define PARAMETER_29_DTYPE     uint16_T
#define PARAMETER_29_COMPLEX   COMPLEX_NO
/* Parameter  31 */
#define PARAMETER_30_NAME      rpi_init7_length
#define PARAMETER_30_DTYPE     uint8_T
#define PARAMETER_30_COMPLEX   COMPLEX_NO
/* Parameter  32 */
#define PARAMETER_31_NAME      rpi_init7_data
#define PARAMETER_31_DTYPE     real_T
#define PARAMETER_31_COMPLEX   COMPLEX_NO
/* Parameter  33 */
#define PARAMETER_32_NAME      rpi_init8_addr
#define PARAMETER_32_DTYPE     uint16_T
#define PARAMETER_32_COMPLEX   COMPLEX_NO
/* Parameter  34 */
#define PARAMETER_33_NAME      rpi_init8_length
#define PARAMETER_33_DTYPE     uint8_T
#define PARAMETER_33_COMPLEX   COMPLEX_NO
/* Parameter  35 */
#define PARAMETER_34_NAME      rpi_init8_data
#define PARAMETER_34_DTYPE     real_T
#define PARAMETER_34_COMPLEX   COMPLEX_NO
/* Parameter  36 */
#define PARAMETER_35_NAME      rpi_halt1_addr
#define PARAMETER_35_DTYPE     uint16_T
#define PARAMETER_35_COMPLEX   COMPLEX_NO
/* Parameter  37 */
#define PARAMETER_36_NAME      rpi_halt1_length
#define PARAMETER_36_DTYPE     uint8_T
#define PARAMETER_36_COMPLEX   COMPLEX_NO
/* Parameter  38 */
#define PARAMETER_37_NAME      rpi_halt1_data
#define PARAMETER_37_DTYPE     real_T
#define PARAMETER_37_COMPLEX   COMPLEX_NO
/* Parameter  39 */
#define PARAMETER_38_NAME      rpi_halt2_addr
#define PARAMETER_38_DTYPE     uint16_T
#define PARAMETER_38_COMPLEX   COMPLEX_NO
/* Parameter  40 */
#define PARAMETER_39_NAME      rpi_halt2_length
#define PARAMETER_39_DTYPE     uint8_T
#define PARAMETER_39_COMPLEX   COMPLEX_NO
/* Parameter  41 */
#define PARAMETER_40_NAME      rpi_halt2_data
#define PARAMETER_40_DTYPE     real_T
#define PARAMETER_40_COMPLEX   COMPLEX_NO

#define SAMPLE_TIME_0        rpi_Ts
#define NUM_DISC_STATES      0
#define DISC_STATES_IC       [0]
#define NUM_CONT_STATES      0
#define CONT_STATES_IC       [0]

#define SFUNWIZ_GENERATE_TLC 1
#define SOURCEFILES "__SFB__"
#define PANELINDEX           6
#define USE_SIMSTRUCT        0
#define SHOW_COMPILE_STEPS   0                   
#define CREATE_DEBUG_MEXFILE 0
#define SAVE_CODE_ONLY       0
#define SFUNWIZ_REVISION     3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"
#define PARAM_DEF0(S) ssGetSFcnParam(S, 0)
#define PARAM_DEF1(S) ssGetSFcnParam(S, 1)
#define PARAM_DEF2(S) ssGetSFcnParam(S, 2)
#define PARAM_DEF3(S) ssGetSFcnParam(S, 3)
#define PARAM_DEF4(S) ssGetSFcnParam(S, 4)
#define PARAM_DEF5(S) ssGetSFcnParam(S, 5)
#define PARAM_DEF6(S) ssGetSFcnParam(S, 6)
#define PARAM_DEF7(S) ssGetSFcnParam(S, 7)
#define PARAM_DEF8(S) ssGetSFcnParam(S, 8)
#define PARAM_DEF9(S) ssGetSFcnParam(S, 9)
#define PARAM_DEF10(S) ssGetSFcnParam(S, 10)
#define PARAM_DEF11(S) ssGetSFcnParam(S, 11)
#define PARAM_DEF12(S) ssGetSFcnParam(S, 12)
#define PARAM_DEF13(S) ssGetSFcnParam(S, 13)
#define PARAM_DEF14(S) ssGetSFcnParam(S, 14)
#define PARAM_DEF15(S) ssGetSFcnParam(S, 15)
#define PARAM_DEF16(S) ssGetSFcnParam(S, 16)
#define PARAM_DEF17(S) ssGetSFcnParam(S, 17)
#define PARAM_DEF18(S) ssGetSFcnParam(S, 18)
#define PARAM_DEF19(S) ssGetSFcnParam(S, 19)
#define PARAM_DEF20(S) ssGetSFcnParam(S, 20)
#define PARAM_DEF21(S) ssGetSFcnParam(S, 21)
#define PARAM_DEF22(S) ssGetSFcnParam(S, 22)
#define PARAM_DEF23(S) ssGetSFcnParam(S, 23)
#define PARAM_DEF24(S) ssGetSFcnParam(S, 24)
#define PARAM_DEF25(S) ssGetSFcnParam(S, 25)
#define PARAM_DEF26(S) ssGetSFcnParam(S, 26)
#define PARAM_DEF27(S) ssGetSFcnParam(S, 27)
#define PARAM_DEF28(S) ssGetSFcnParam(S, 28)
#define PARAM_DEF29(S) ssGetSFcnParam(S, 29)
#define PARAM_DEF30(S) ssGetSFcnParam(S, 30)
#define PARAM_DEF31(S) ssGetSFcnParam(S, 31)
#define PARAM_DEF32(S) ssGetSFcnParam(S, 32)
#define PARAM_DEF33(S) ssGetSFcnParam(S, 33)
#define PARAM_DEF34(S) ssGetSFcnParam(S, 34)
#define PARAM_DEF35(S) ssGetSFcnParam(S, 35)
#define PARAM_DEF36(S) ssGetSFcnParam(S, 36)
#define PARAM_DEF37(S) ssGetSFcnParam(S, 37)
#define PARAM_DEF38(S) ssGetSFcnParam(S, 38)
#define PARAM_DEF39(S) ssGetSFcnParam(S, 39)
#define PARAM_DEF40(S) ssGetSFcnParam(S, 40)

#define IS_PARAM_DOUBLE(pVal) (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsDouble(pVal))

#define IS_PARAM_UINT8(pVal) (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsUint8(pVal))

#define IS_PARAM_UINT32(pVal) (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsUint32(pVal))

#define IS_PARAM_UINT16(pVal) (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsUint16(pVal))

extern void rpi_sfun_dxl_Outputs_wrapper(const real_T *u1,
                          const real_T *u2,
                          const real_T *u3,
                          const real_T *u4,
                          const real_T *u5,
                          const real_T *u6,
                          const real_T *u7,
                          const real_T *u8,
                          const real_T *u9,
                          const real_T *u10,
                          real_T *y1,
                          real_T *y2,
                          real_T *y3,
                          real_T *y4,
                          real_T *y5,
                          real_T *y6,
                          real_T *y7,
                          real_T *y8,
                          real_T *y9,
                          real_T *y10  , 
                          const real_T  *rpi_Ts, const int_T  p_width0, 
                          const uint8_T  *rpi_portname, const int_T  p_width1, 
                          const uint32_T  *rpi_baudrate, const int_T  p_width2, 
                          const uint8_T  *rpi_startid, const int_T  p_width3, 
                          const uint8_T  *rpi_nbid, const int_T  p_width4, 
                          const uint8_T  *rpi_proto, const int_T  p_width5, 
                          const uint16_T  *rpi_write_addr, const int_T  p_width6, 
                          const uint8_T  *rpi_write_length, const int_T  p_width7, 
                          const uint16_T  *rpi_read_addr, const int_T  p_width8, 
                          const uint8_T  *rpi_read_length, const int_T  p_width9, 
                          const uint8_T  *rpi_read_sign, const int_T  p_width10, 
                          const uint16_T  *rpi_init1_addr, const int_T  p_width11, 
                          const uint8_T  *rpi_init1_length, const int_T  p_width12, 
                          const real_T  *rpi_init1_data, const int_T  p_width13, 
                          const uint16_T  *rpi_init2_addr, const int_T  p_width14, 
                          const uint8_T  *rpi_init2_length, const int_T  p_width15, 
                          const real_T  *rpi_init2_data, const int_T  p_width16, 
                          const uint16_T  *rpi_init3_addr, const int_T  p_width17, 
                          const uint8_T  *rpi_init3_length, const int_T  p_width18, 
                          const real_T  *rpi_init3_data, const int_T  p_width19, 
                          const uint16_T  *rpi_init4_addr, const int_T  p_width20, 
                          const uint8_T  *rpi_init4_length, const int_T  p_width21, 
                          const real_T  *rpi_init4_data, const int_T  p_width22, 
                          const uint16_T  *rpi_init5_addr, const int_T  p_width23, 
                          const uint8_T  *rpi_init5_length, const int_T  p_width24, 
                          const real_T  *rpi_init5_data, const int_T  p_width25, 
                          const uint16_T  *rpi_init6_addr, const int_T  p_width26, 
                          const uint8_T  *rpi_init6_length, const int_T  p_width27, 
                          const real_T  *rpi_init6_data, const int_T  p_width28, 
                          const uint16_T  *rpi_init7_addr, const int_T  p_width29, 
                          const uint8_T  *rpi_init7_length, const int_T  p_width30, 
                          const real_T  *rpi_init7_data, const int_T  p_width31, 
                          const uint16_T  *rpi_init8_addr, const int_T  p_width32, 
                          const uint8_T  *rpi_init8_length, const int_T  p_width33, 
                          const real_T  *rpi_init8_data, const int_T  p_width34, 
                          const uint16_T  *rpi_halt1_addr, const int_T  p_width35, 
                          const uint8_T  *rpi_halt1_length, const int_T  p_width36, 
                          const real_T  *rpi_halt1_data, const int_T  p_width37, 
                          const uint16_T  *rpi_halt2_addr, const int_T  p_width38, 
                          const uint8_T  *rpi_halt2_length, const int_T  p_width39, 
                          const real_T  *rpi_halt2_data,  const int_T p_width40);

/*====================*
 * S-function methods *
 *====================*/
#define MDL_CHECK_PARAMETERS
 #if defined(MDL_CHECK_PARAMETERS) && defined(MATLAB_MEX_FILE)
   /* Function: mdlCheckParameters =============================================
     * Abstract:
     *    Validate our parameters to verify they are okay.
     */
    static void mdlCheckParameters(SimStruct *S)
    {
     int paramIndex  = 0;
     bool validParam = false;
     /* All parameters must match the S-function Builder Dialog */
     

	 {
	  const mxArray *pVal0 = ssGetSFcnParam(S,0);
	  if (!mxIsDouble(pVal0)) {
	    ssSetErrorStatus(S,"Sample time parameter rpi_Ts must be of type double");
	    return; 
	  }
	 }

	 {
	  const mxArray *pVal0 = ssGetSFcnParam(S,0);
	  if (!IS_PARAM_DOUBLE(pVal0)) {
	    validParam = true;
	    paramIndex = 0;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal1 = ssGetSFcnParam(S,1);
	  if (!IS_PARAM_UINT8(pVal1)) {
	    validParam = true;
	    paramIndex = 1;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal2 = ssGetSFcnParam(S,2);
	  if (!IS_PARAM_UINT32(pVal2)) {
	    validParam = true;
	    paramIndex = 2;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal3 = ssGetSFcnParam(S,3);
	  if (!IS_PARAM_UINT8(pVal3)) {
	    validParam = true;
	    paramIndex = 3;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal4 = ssGetSFcnParam(S,4);
	  if (!IS_PARAM_UINT8(pVal4)) {
	    validParam = true;
	    paramIndex = 4;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal5 = ssGetSFcnParam(S,5);
	  if (!IS_PARAM_UINT8(pVal5)) {
	    validParam = true;
	    paramIndex = 5;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal6 = ssGetSFcnParam(S,6);
	  if (!IS_PARAM_UINT16(pVal6)) {
	    validParam = true;
	    paramIndex = 6;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal7 = ssGetSFcnParam(S,7);
	  if (!IS_PARAM_UINT8(pVal7)) {
	    validParam = true;
	    paramIndex = 7;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal8 = ssGetSFcnParam(S,8);
	  if (!IS_PARAM_UINT16(pVal8)) {
	    validParam = true;
	    paramIndex = 8;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal9 = ssGetSFcnParam(S,9);
	  if (!IS_PARAM_UINT8(pVal9)) {
	    validParam = true;
	    paramIndex = 9;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal10 = ssGetSFcnParam(S,10);
	  if (!IS_PARAM_UINT8(pVal10)) {
	    validParam = true;
	    paramIndex = 10;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal11 = ssGetSFcnParam(S,11);
	  if (!IS_PARAM_UINT16(pVal11)) {
	    validParam = true;
	    paramIndex = 11;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal12 = ssGetSFcnParam(S,12);
	  if (!IS_PARAM_UINT8(pVal12)) {
	    validParam = true;
	    paramIndex = 12;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal13 = ssGetSFcnParam(S,13);
	  if (!IS_PARAM_DOUBLE(pVal13)) {
	    validParam = true;
	    paramIndex = 13;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal14 = ssGetSFcnParam(S,14);
	  if (!IS_PARAM_UINT16(pVal14)) {
	    validParam = true;
	    paramIndex = 14;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal15 = ssGetSFcnParam(S,15);
	  if (!IS_PARAM_UINT8(pVal15)) {
	    validParam = true;
	    paramIndex = 15;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal16 = ssGetSFcnParam(S,16);
	  if (!IS_PARAM_DOUBLE(pVal16)) {
	    validParam = true;
	    paramIndex = 16;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal17 = ssGetSFcnParam(S,17);
	  if (!IS_PARAM_UINT16(pVal17)) {
	    validParam = true;
	    paramIndex = 17;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal18 = ssGetSFcnParam(S,18);
	  if (!IS_PARAM_UINT8(pVal18)) {
	    validParam = true;
	    paramIndex = 18;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal19 = ssGetSFcnParam(S,19);
	  if (!IS_PARAM_DOUBLE(pVal19)) {
	    validParam = true;
	    paramIndex = 19;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal20 = ssGetSFcnParam(S,20);
	  if (!IS_PARAM_UINT16(pVal20)) {
	    validParam = true;
	    paramIndex = 20;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal21 = ssGetSFcnParam(S,21);
	  if (!IS_PARAM_UINT8(pVal21)) {
	    validParam = true;
	    paramIndex = 21;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal22 = ssGetSFcnParam(S,22);
	  if (!IS_PARAM_DOUBLE(pVal22)) {
	    validParam = true;
	    paramIndex = 22;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal23 = ssGetSFcnParam(S,23);
	  if (!IS_PARAM_UINT16(pVal23)) {
	    validParam = true;
	    paramIndex = 23;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal24 = ssGetSFcnParam(S,24);
	  if (!IS_PARAM_UINT8(pVal24)) {
	    validParam = true;
	    paramIndex = 24;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal25 = ssGetSFcnParam(S,25);
	  if (!IS_PARAM_DOUBLE(pVal25)) {
	    validParam = true;
	    paramIndex = 25;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal26 = ssGetSFcnParam(S,26);
	  if (!IS_PARAM_UINT16(pVal26)) {
	    validParam = true;
	    paramIndex = 26;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal27 = ssGetSFcnParam(S,27);
	  if (!IS_PARAM_UINT8(pVal27)) {
	    validParam = true;
	    paramIndex = 27;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal28 = ssGetSFcnParam(S,28);
	  if (!IS_PARAM_DOUBLE(pVal28)) {
	    validParam = true;
	    paramIndex = 28;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal29 = ssGetSFcnParam(S,29);
	  if (!IS_PARAM_UINT16(pVal29)) {
	    validParam = true;
	    paramIndex = 29;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal30 = ssGetSFcnParam(S,30);
	  if (!IS_PARAM_UINT8(pVal30)) {
	    validParam = true;
	    paramIndex = 30;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal31 = ssGetSFcnParam(S,31);
	  if (!IS_PARAM_DOUBLE(pVal31)) {
	    validParam = true;
	    paramIndex = 31;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal32 = ssGetSFcnParam(S,32);
	  if (!IS_PARAM_UINT16(pVal32)) {
	    validParam = true;
	    paramIndex = 32;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal33 = ssGetSFcnParam(S,33);
	  if (!IS_PARAM_UINT8(pVal33)) {
	    validParam = true;
	    paramIndex = 33;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal34 = ssGetSFcnParam(S,34);
	  if (!IS_PARAM_DOUBLE(pVal34)) {
	    validParam = true;
	    paramIndex = 34;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal35 = ssGetSFcnParam(S,35);
	  if (!IS_PARAM_UINT16(pVal35)) {
	    validParam = true;
	    paramIndex = 35;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal36 = ssGetSFcnParam(S,36);
	  if (!IS_PARAM_UINT8(pVal36)) {
	    validParam = true;
	    paramIndex = 36;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal37 = ssGetSFcnParam(S,37);
	  if (!IS_PARAM_DOUBLE(pVal37)) {
	    validParam = true;
	    paramIndex = 37;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal38 = ssGetSFcnParam(S,38);
	  if (!IS_PARAM_UINT16(pVal38)) {
	    validParam = true;
	    paramIndex = 38;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal39 = ssGetSFcnParam(S,39);
	  if (!IS_PARAM_UINT8(pVal39)) {
	    validParam = true;
	    paramIndex = 39;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal40 = ssGetSFcnParam(S,40);
	  if (!IS_PARAM_DOUBLE(pVal40)) {
	    validParam = true;
	    paramIndex = 40;
	    goto EXIT_POINT;
	  }
	 }
      
     EXIT_POINT:
      if (validParam) {
          char parameterErrorMsg[1024];
          sprintf(parameterErrorMsg, "The data type and or complexity of parameter  %d does not match the "
                  "information specified in the S-function Builder dialog. "
                  "For non-double parameters you will need to cast them using int8, int16, "
                  "int32, uint8, uint16, uint32 or boolean.", paramIndex + 1);
	  ssSetErrorStatus(S,parameterErrorMsg);
      }
	return;
    }
 #endif /* MDL_CHECK_PARAMETERS */
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{

    DECL_AND_INIT_DIMSINFO(inputDimsInfo);
    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS);  /* Number of expected parameters */
      #if defined(MATLAB_MEX_FILE)
	if (ssGetNumSFcnParams(S) == ssGetSFcnParamsCount(S)) {
	  mdlCheckParameters(S);
	  if (ssGetErrorStatus(S) != NULL) {
	    return;
	  }
	 } else {
	   return; /* Parameter mismatch will be reported by Simulink */
	 }
      #endif

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);

    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;
    /*Input Port 0 */
    ssSetInputPortWidth(S,  0, INPUT_0_WIDTH); /* */
    ssSetInputPortDataType(S, 0, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  0, INPUT_0_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 0, 1); /*direct input signal access*/

    /*Input Port 1 */
    ssSetInputPortWidth(S,  1, INPUT_1_WIDTH); /* */
    ssSetInputPortDataType(S, 1, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  1, INPUT_1_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 1, 1); /*direct input signal access*/

    /*Input Port 2 */
    ssSetInputPortWidth(S,  2, INPUT_2_WIDTH); /* */
    ssSetInputPortDataType(S, 2, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  2, INPUT_2_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 2, 1); /*direct input signal access*/

    /*Input Port 3 */
    ssSetInputPortWidth(S,  3, INPUT_3_WIDTH); /* */
    ssSetInputPortDataType(S, 3, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  3, INPUT_3_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 3, INPUT_3_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 3, 1); /*direct input signal access*/

    /*Input Port 4 */
    ssSetInputPortWidth(S,  4, INPUT_4_WIDTH); /* */
    ssSetInputPortDataType(S, 4, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  4, INPUT_4_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 4, INPUT_4_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 4, 1); /*direct input signal access*/

    /*Input Port 5 */
    ssSetInputPortWidth(S,  5, INPUT_5_WIDTH); /* */
    ssSetInputPortDataType(S, 5, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  5, INPUT_5_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 5, INPUT_5_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 5, 1); /*direct input signal access*/

    /*Input Port 6 */
    ssSetInputPortWidth(S,  6, INPUT_6_WIDTH); /* */
    ssSetInputPortDataType(S, 6, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  6, INPUT_6_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 6, INPUT_6_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 6, 1); /*direct input signal access*/

    /*Input Port 7 */
    ssSetInputPortWidth(S,  7, INPUT_7_WIDTH); /* */
    ssSetInputPortDataType(S, 7, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  7, INPUT_7_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 7, INPUT_7_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 7, 1); /*direct input signal access*/

    /*Input Port 8 */
    ssSetInputPortWidth(S,  8, INPUT_8_WIDTH); /* */
    ssSetInputPortDataType(S, 8, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  8, INPUT_8_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 8, INPUT_8_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 8, 1); /*direct input signal access*/

    /*Input Port 9 */
    ssSetInputPortWidth(S,  9, INPUT_9_WIDTH); /* */
    ssSetInputPortDataType(S, 9, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  9, INPUT_9_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 9, INPUT_9_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 9, 1); /*direct input signal access*/


    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    /* Output Port 0 */
    ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);
    /* Output Port 1 */
    ssSetOutputPortWidth(S, 1, OUTPUT_1_WIDTH);
    ssSetOutputPortDataType(S, 1, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);
    /* Output Port 2 */
    ssSetOutputPortWidth(S, 2, OUTPUT_2_WIDTH);
    ssSetOutputPortDataType(S, 2, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);
    /* Output Port 3 */
    ssSetOutputPortWidth(S, 3, OUTPUT_3_WIDTH);
    ssSetOutputPortDataType(S, 3, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 3, OUTPUT_3_COMPLEX);
    /* Output Port 4 */
    ssSetOutputPortWidth(S, 4, OUTPUT_4_WIDTH);
    ssSetOutputPortDataType(S, 4, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 4, OUTPUT_4_COMPLEX);
    /* Output Port 5 */
    ssSetOutputPortWidth(S, 5, OUTPUT_5_WIDTH);
    ssSetOutputPortDataType(S, 5, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 5, OUTPUT_5_COMPLEX);
    /* Output Port 6 */
    ssSetOutputPortWidth(S, 6, OUTPUT_6_WIDTH);
    ssSetOutputPortDataType(S, 6, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 6, OUTPUT_6_COMPLEX);
    /* Output Port 7 */
    ssSetOutputPortWidth(S, 7, OUTPUT_7_WIDTH);
    ssSetOutputPortDataType(S, 7, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 7, OUTPUT_7_COMPLEX);
    /* Output Port 8 */
    ssSetOutputPortWidth(S, 8, OUTPUT_8_WIDTH);
    ssSetOutputPortDataType(S, 8, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 8, OUTPUT_8_COMPLEX);
    /* Output Port 9 */
    ssSetOutputPortWidth(S, 9, OUTPUT_9_WIDTH);
    ssSetOutputPortDataType(S, 9, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 9, OUTPUT_9_COMPLEX);

    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumPWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                     SS_OPTION_USE_TLC_WITH_ACCELERATOR | 
		     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

# define MDL_SET_INPUT_PORT_FRAME_DATA
static void mdlSetInputPortFrameData(SimStruct  *S, 
                                     int_T      port,
                                     Frame_T    frameData)
{
    ssSetInputPortFrameData(S, port, frameData);
}
/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, *mxGetPr(ssGetSFcnParam(S, 0)));
    ssSetOffsetTime(S, 0, 0.0);
}


#define MDL_START  /* Change to #undef to remove function */
#if defined(MDL_START) 
  /* Function: mdlStart =======================================================
   * Abstract:
   *    This function is called once at start of model execution. If you
   *    have states that should be initialized once, this is the place
   *    to do it.
   */
  static void mdlStart(SimStruct *S)
  {
  }
#endif /*  MDL_START */

#define MDL_SET_INPUT_PORT_DATA_TYPE
static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetInputPortDataType( S, 0, dType);
}
#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType( S, 0, SS_DOUBLE);
 ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}
/* Function: mdlOutputs =======================================================
 *
*/
static void mdlOutputs(SimStruct *S, int_T tid)
{
    const real_T   *u1  = (const real_T*) ssGetInputPortSignal(S,0);
    const real_T   *u2  = (const real_T*) ssGetInputPortSignal(S,1);
    const real_T   *u3  = (const real_T*) ssGetInputPortSignal(S,2);
    const real_T   *u4  = (const real_T*) ssGetInputPortSignal(S,3);
    const real_T   *u5  = (const real_T*) ssGetInputPortSignal(S,4);
    const real_T   *u6  = (const real_T*) ssGetInputPortSignal(S,5);
    const real_T   *u7  = (const real_T*) ssGetInputPortSignal(S,6);
    const real_T   *u8  = (const real_T*) ssGetInputPortSignal(S,7);
    const real_T   *u9  = (const real_T*) ssGetInputPortSignal(S,8);
    const real_T   *u10  = (const real_T*) ssGetInputPortSignal(S,9);
    real_T        *y1  = (real_T *)ssGetOutputPortRealSignal(S,0);
    real_T        *y2  = (real_T *)ssGetOutputPortRealSignal(S,1);
    real_T        *y3  = (real_T *)ssGetOutputPortRealSignal(S,2);
    real_T        *y4  = (real_T *)ssGetOutputPortRealSignal(S,3);
    real_T        *y5  = (real_T *)ssGetOutputPortRealSignal(S,4);
    real_T        *y6  = (real_T *)ssGetOutputPortRealSignal(S,5);
    real_T        *y7  = (real_T *)ssGetOutputPortRealSignal(S,6);
    real_T        *y8  = (real_T *)ssGetOutputPortRealSignal(S,7);
    real_T        *y9  = (real_T *)ssGetOutputPortRealSignal(S,8);
    real_T        *y10  = (real_T *)ssGetOutputPortRealSignal(S,9);
    const int_T   p_width0  = mxGetNumberOfElements(PARAM_DEF0(S));
    const int_T   p_width1  = mxGetNumberOfElements(PARAM_DEF1(S));
    const int_T   p_width2  = mxGetNumberOfElements(PARAM_DEF2(S));
    const int_T   p_width3  = mxGetNumberOfElements(PARAM_DEF3(S));
    const int_T   p_width4  = mxGetNumberOfElements(PARAM_DEF4(S));
    const int_T   p_width5  = mxGetNumberOfElements(PARAM_DEF5(S));
    const int_T   p_width6  = mxGetNumberOfElements(PARAM_DEF6(S));
    const int_T   p_width7  = mxGetNumberOfElements(PARAM_DEF7(S));
    const int_T   p_width8  = mxGetNumberOfElements(PARAM_DEF8(S));
    const int_T   p_width9  = mxGetNumberOfElements(PARAM_DEF9(S));
    const int_T   p_width10  = mxGetNumberOfElements(PARAM_DEF10(S));
    const int_T   p_width11  = mxGetNumberOfElements(PARAM_DEF11(S));
    const int_T   p_width12  = mxGetNumberOfElements(PARAM_DEF12(S));
    const int_T   p_width13  = mxGetNumberOfElements(PARAM_DEF13(S));
    const int_T   p_width14  = mxGetNumberOfElements(PARAM_DEF14(S));
    const int_T   p_width15  = mxGetNumberOfElements(PARAM_DEF15(S));
    const int_T   p_width16  = mxGetNumberOfElements(PARAM_DEF16(S));
    const int_T   p_width17  = mxGetNumberOfElements(PARAM_DEF17(S));
    const int_T   p_width18  = mxGetNumberOfElements(PARAM_DEF18(S));
    const int_T   p_width19  = mxGetNumberOfElements(PARAM_DEF19(S));
    const int_T   p_width20  = mxGetNumberOfElements(PARAM_DEF20(S));
    const int_T   p_width21  = mxGetNumberOfElements(PARAM_DEF21(S));
    const int_T   p_width22  = mxGetNumberOfElements(PARAM_DEF22(S));
    const int_T   p_width23  = mxGetNumberOfElements(PARAM_DEF23(S));
    const int_T   p_width24  = mxGetNumberOfElements(PARAM_DEF24(S));
    const int_T   p_width25  = mxGetNumberOfElements(PARAM_DEF25(S));
    const int_T   p_width26  = mxGetNumberOfElements(PARAM_DEF26(S));
    const int_T   p_width27  = mxGetNumberOfElements(PARAM_DEF27(S));
    const int_T   p_width28  = mxGetNumberOfElements(PARAM_DEF28(S));
    const int_T   p_width29  = mxGetNumberOfElements(PARAM_DEF29(S));
    const int_T   p_width30  = mxGetNumberOfElements(PARAM_DEF30(S));
    const int_T   p_width31  = mxGetNumberOfElements(PARAM_DEF31(S));
    const int_T   p_width32  = mxGetNumberOfElements(PARAM_DEF32(S));
    const int_T   p_width33  = mxGetNumberOfElements(PARAM_DEF33(S));
    const int_T   p_width34  = mxGetNumberOfElements(PARAM_DEF34(S));
    const int_T   p_width35  = mxGetNumberOfElements(PARAM_DEF35(S));
    const int_T   p_width36  = mxGetNumberOfElements(PARAM_DEF36(S));
    const int_T   p_width37  = mxGetNumberOfElements(PARAM_DEF37(S));
    const int_T   p_width38  = mxGetNumberOfElements(PARAM_DEF38(S));
    const int_T   p_width39  = mxGetNumberOfElements(PARAM_DEF39(S));
    const int_T   p_width40  = mxGetNumberOfElements(PARAM_DEF40(S));
    const real_T  *rpi_Ts  = (const real_T *)mxGetData(PARAM_DEF0(S));
    const uint8_T  *rpi_portname  = (const uint8_T *)mxGetData(PARAM_DEF1(S));
    const uint32_T  *rpi_baudrate  = (const uint32_T *)mxGetData(PARAM_DEF2(S));
    const uint8_T  *rpi_startid  = (const uint8_T *)mxGetData(PARAM_DEF3(S));
    const uint8_T  *rpi_nbid  = (const uint8_T *)mxGetData(PARAM_DEF4(S));
    const uint8_T  *rpi_proto  = (const uint8_T *)mxGetData(PARAM_DEF5(S));
    const uint16_T  *rpi_write_addr  = (const uint16_T *)mxGetData(PARAM_DEF6(S));
    const uint8_T  *rpi_write_length  = (const uint8_T *)mxGetData(PARAM_DEF7(S));
    const uint16_T  *rpi_read_addr  = (const uint16_T *)mxGetData(PARAM_DEF8(S));
    const uint8_T  *rpi_read_length  = (const uint8_T *)mxGetData(PARAM_DEF9(S));
    const uint8_T  *rpi_read_sign  = (const uint8_T *)mxGetData(PARAM_DEF10(S));
    const uint16_T  *rpi_init1_addr  = (const uint16_T *)mxGetData(PARAM_DEF11(S));
    const uint8_T  *rpi_init1_length  = (const uint8_T *)mxGetData(PARAM_DEF12(S));
    const real_T  *rpi_init1_data  = (const real_T *)mxGetData(PARAM_DEF13(S));
    const uint16_T  *rpi_init2_addr  = (const uint16_T *)mxGetData(PARAM_DEF14(S));
    const uint8_T  *rpi_init2_length  = (const uint8_T *)mxGetData(PARAM_DEF15(S));
    const real_T  *rpi_init2_data  = (const real_T *)mxGetData(PARAM_DEF16(S));
    const uint16_T  *rpi_init3_addr  = (const uint16_T *)mxGetData(PARAM_DEF17(S));
    const uint8_T  *rpi_init3_length  = (const uint8_T *)mxGetData(PARAM_DEF18(S));
    const real_T  *rpi_init3_data  = (const real_T *)mxGetData(PARAM_DEF19(S));
    const uint16_T  *rpi_init4_addr  = (const uint16_T *)mxGetData(PARAM_DEF20(S));
    const uint8_T  *rpi_init4_length  = (const uint8_T *)mxGetData(PARAM_DEF21(S));
    const real_T  *rpi_init4_data  = (const real_T *)mxGetData(PARAM_DEF22(S));
    const uint16_T  *rpi_init5_addr  = (const uint16_T *)mxGetData(PARAM_DEF23(S));
    const uint8_T  *rpi_init5_length  = (const uint8_T *)mxGetData(PARAM_DEF24(S));
    const real_T  *rpi_init5_data  = (const real_T *)mxGetData(PARAM_DEF25(S));
    const uint16_T  *rpi_init6_addr  = (const uint16_T *)mxGetData(PARAM_DEF26(S));
    const uint8_T  *rpi_init6_length  = (const uint8_T *)mxGetData(PARAM_DEF27(S));
    const real_T  *rpi_init6_data  = (const real_T *)mxGetData(PARAM_DEF28(S));
    const uint16_T  *rpi_init7_addr  = (const uint16_T *)mxGetData(PARAM_DEF29(S));
    const uint8_T  *rpi_init7_length  = (const uint8_T *)mxGetData(PARAM_DEF30(S));
    const real_T  *rpi_init7_data  = (const real_T *)mxGetData(PARAM_DEF31(S));
    const uint16_T  *rpi_init8_addr  = (const uint16_T *)mxGetData(PARAM_DEF32(S));
    const uint8_T  *rpi_init8_length  = (const uint8_T *)mxGetData(PARAM_DEF33(S));
    const real_T  *rpi_init8_data  = (const real_T *)mxGetData(PARAM_DEF34(S));
    const uint16_T  *rpi_halt1_addr  = (const uint16_T *)mxGetData(PARAM_DEF35(S));
    const uint8_T  *rpi_halt1_length  = (const uint8_T *)mxGetData(PARAM_DEF36(S));
    const real_T  *rpi_halt1_data  = (const real_T *)mxGetData(PARAM_DEF37(S));
    const uint16_T  *rpi_halt2_addr  = (const uint16_T *)mxGetData(PARAM_DEF38(S));
    const uint8_T  *rpi_halt2_length  = (const uint8_T *)mxGetData(PARAM_DEF39(S));
    const real_T  *rpi_halt2_data  = (const real_T *)mxGetData(PARAM_DEF40(S));

    rpi_sfun_dxl_Outputs_wrapper(u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, y1, y2, y3, y4, y5, y6, y7, y8, y9, y10, rpi_Ts, p_width0, rpi_portname, p_width1, rpi_baudrate, p_width2, rpi_startid, p_width3, rpi_nbid, p_width4, rpi_proto, p_width5, rpi_write_addr, p_width6, rpi_write_length, p_width7, rpi_read_addr, p_width8, rpi_read_length, p_width9, rpi_read_sign, p_width10, rpi_init1_addr, p_width11, rpi_init1_length, p_width12, rpi_init1_data, p_width13, rpi_init2_addr, p_width14, rpi_init2_length, p_width15, rpi_init2_data, p_width16, rpi_init3_addr, p_width17, rpi_init3_length, p_width18, rpi_init3_data, p_width19, rpi_init4_addr, p_width20, rpi_init4_length, p_width21, rpi_init4_data, p_width22, rpi_init5_addr, p_width23, rpi_init5_length, p_width24, rpi_init5_data, p_width25, rpi_init6_addr, p_width26, rpi_init6_length, p_width27, rpi_init6_data, p_width28, rpi_init7_addr, p_width29, rpi_init7_length, p_width30, rpi_init7_data, p_width31, rpi_init8_addr, p_width32, rpi_init8_length, p_width33, rpi_init8_data, p_width34, rpi_halt1_addr, p_width35, rpi_halt1_length, p_width36, rpi_halt1_data, p_width37, rpi_halt2_addr, p_width38, rpi_halt2_length, p_width39, rpi_halt2_data, p_width40);
}



/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
}
#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif


