/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Wed Aug 31 16:16:04 2016
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void rpi_sfun_dxl_Outputs_wrapper(const real_T *u1,
                          const real_T *u2,
                          const real_T *u3,
                          const real_T *u4,
                          const real_T *u5,
                          const real_T *u6,
                          const real_T *u7,
                          const real_T *u8,
                          const real_T *u9,
                          const real_T *u10,
                          real_T *y1,
                          real_T *y2,
                          real_T *y3,
                          real_T *y4,
                          real_T *y5,
                          real_T *y6,
                          real_T *y7,
                          real_T *y8,
                          real_T *y9,
                          real_T *y10  , 
                          const real_T  *rpi_Ts, const int_T  p_width0, 
                          const uint8_T  *rpi_portname, const int_T  p_width1, 
                          const uint32_T  *rpi_baudrate, const int_T  p_width2, 
                          const uint8_T  *rpi_startid, const int_T  p_width3, 
                          const uint8_T  *rpi_nbid, const int_T  p_width4, 
                          const uint8_T  *rpi_proto, const int_T  p_width5, 
                          const uint16_T  *rpi_write_addr, const int_T  p_width6, 
                          const uint8_T  *rpi_write_length, const int_T  p_width7, 
                          const uint16_T  *rpi_read_addr, const int_T  p_width8, 
                          const uint8_T  *rpi_read_length, const int_T  p_width9, 
                          const uint8_T  *rpi_read_sign, const int_T  p_width10, 
                          const uint16_T  *rpi_init1_addr, const int_T  p_width11, 
                          const uint8_T  *rpi_init1_length, const int_T  p_width12, 
                          const real_T  *rpi_init1_data, const int_T  p_width13, 
                          const uint16_T  *rpi_init2_addr, const int_T  p_width14, 
                          const uint8_T  *rpi_init2_length, const int_T  p_width15, 
                          const real_T  *rpi_init2_data, const int_T  p_width16, 
                          const uint16_T  *rpi_init3_addr, const int_T  p_width17, 
                          const uint8_T  *rpi_init3_length, const int_T  p_width18, 
                          const real_T  *rpi_init3_data, const int_T  p_width19, 
                          const uint16_T  *rpi_init4_addr, const int_T  p_width20, 
                          const uint8_T  *rpi_init4_length, const int_T  p_width21, 
                          const real_T  *rpi_init4_data, const int_T  p_width22, 
                          const uint16_T  *rpi_init5_addr, const int_T  p_width23, 
                          const uint8_T  *rpi_init5_length, const int_T  p_width24, 
                          const real_T  *rpi_init5_data, const int_T  p_width25, 
                          const uint16_T  *rpi_init6_addr, const int_T  p_width26, 
                          const uint8_T  *rpi_init6_length, const int_T  p_width27, 
                          const real_T  *rpi_init6_data, const int_T  p_width28, 
                          const uint16_T  *rpi_init7_addr, const int_T  p_width29, 
                          const uint8_T  *rpi_init7_length, const int_T  p_width30, 
                          const real_T  *rpi_init7_data, const int_T  p_width31, 
                          const uint16_T  *rpi_init8_addr, const int_T  p_width32, 
                          const uint8_T  *rpi_init8_length, const int_T  p_width33, 
                          const real_T  *rpi_init8_data, const int_T  p_width34, 
                          const uint16_T  *rpi_halt1_addr, const int_T  p_width35, 
                          const uint8_T  *rpi_halt1_length, const int_T  p_width36, 
                          const real_T  *rpi_halt1_data, const int_T  p_width37, 
                          const uint16_T  *rpi_halt2_addr, const int_T  p_width38, 
                          const uint8_T  *rpi_halt2_length, const int_T  p_width39, 
                          const real_T  *rpi_halt2_data,  const int_T p_width40)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* This sample sets the output equal to the input
         y0[0] = u0[0];
For complex signals use: y0[0].re = u0[0].re;
                         y0[0].im = u0[0].im;
                         y1[0].re = u1[0].re;
                         y1[0].im = u1[0].im;*/
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
