/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Tue May 22 12:04:58 2018
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
#ifndef MATLAB_MEX_FILE
#include "trex.c"
#endif
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void rpi_sfun_trex_Outputs_wrapper(const real_T *u1,
                          const real_T *u2,
                          real_T *Err  , 
                          const int8_T  *rpi_trex_port, const int_T  p_width0, 
                          const uint8_T  *rpi_trex_id, const int_T  p_width1, 
                          const real_T  *rpi_Ts,  const int_T p_width2)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
#ifdef MATLAB_MEX_FILE
  Err[0] = 0;
  return;

#else
  #define PORT_NAME_SIZE  255
  #define PORT_NAME_INT   "/dev/ttyS"
  #define PORT_NAME_USB   "/dev/ttyUSB"
          
  char        port_name[PORT_NAME_SIZE];
  signed char out1, out2;
  int         ret;
  
  Err[0] = 0;
  
  if ( ( p_width0 > 1 ) || ( p_width1 > 1 ) || ( p_width2 > 1 ) )	{
    fprintf( stderr, "** Multiple rates not allowed in this block **\n" );
    Err[0] = 1;
    return;
  }

  if ( *rpi_Ts < 0.01 )	{
    fprintf( stderr, "** Max sampling rate = 100Hz **\n" );
    Err[0] = 2;
    return;
  
  if ( *rpi_trex_port < 0 )
    snprintf( port_name, "%s%d", PORT_NAME_INT, -(*rpi_trex_port+1) );
  else
    snprintf( port_name, "%s%d", PORT_NAME_USB, *rpi_trex_port );
    
  ret = trex_init_port( port_name );
  if ( ret )  {
    Err[0] = 3;
    return;
  }
  
  if ( *u1 > TREX_MAX_DUTY_CYCLE )
    out1 = TREX_MAX_DUTY_CYCLE;
  if ( *u1 < -TREX_MAX_DUTY_CYCLE )
    out1 = -TREX_MAX_DUTY_CYCLE;
  if ( ( *u1 >= -TREX_MAX_DUTY_CYCLE ) && ( *u1 <= TREX_MAX_DUTY_CYCLE ) )
    out1 = (signed char)*u1;
  if ( isnan( *u1 ) )
    out1 = TREX_MIN_DUTY_CYCLE;
  
  if ( *u2 > TREX_MAX_DUTY_CYCLE )
    out2 = TREX_MAX_DUTY_CYCLE;
  if ( *u2 < -TREX_MAX_DUTY_CYCLE )
    out2 = -TREX_MAX_DUTY_CYCLE;
  if ( ( *u2 >= -TREX_MAX_DUTY_CYCLE ) && ( *u2 <= TREX_MAX_DUTY_CYCLE ) )
    out2 = (signed char)*u2;
  if ( isnan( *u2 ) )
    out2 = TREX_MIN_DUTY_CYCLE;
  
  ret = trex_output( *rpi_trex_id, out1, out2 );
  if ( ret )  {
    Err[0] = 4;
    return;
  }
  
  trex_release_port(  );
  }

#endif
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
