/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Thu Jan 29 16:26:35 2015
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>

#ifndef MATLAB_MEX_FILE
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <fcntl.h>
#include <unistd.h>
#include <pthread.h>
#include <sched.h>
#include <linux/sched.h>
#include <sys/stat.h>
#include <semaphore.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/shm.h>

/* Include Polaris API */

#include "polaris.c"

/* rpitdd definitions */

#define RPITDD_ACK_TIMEOUT_MS			10000
#define RPITDD_CHAR_BUF_LEN				255

#define RPITDD_CMD_NOCMD					0
#define RPITDD_CMD_EXIT						1
#define RPITDD_CMD_START					2
#define RPITDD_CMD_STOP						3

/* Polaris specific */

#define RPITDD_POL_STATUS_OK			0			// Pose OK
#define RPITDD_POL_STATUS_PART		1			// Target partially out of volume
#define RPITDD_POL_STATUS_OUT			2			// Target completely out of volume
#define RPITDD_POL_STATUS_INV			3			// Pose invalid

#define RPITDD_CLIENT_NBACQ       2000
#define RPITDD_CLIENT_TUS         10000

struct rpitdd_data					//	Server		Client
{
	unsigned char cmd;				//	R/W				R/W
	unsigned char	started;		//	R/W				R
	
	/* Polaris specific */
	
	// Translation
	double 				x;					//	W					R
	double 				y;					//	W					R
	double 				z;
	
	// Quaternions
	double 				q0;					//	W					R
	double 				qx;					//	W					R
	double 				qy;					//	W					R
	double 				qz;					//	W					R
	
	// Status
	unsigned char	status;			//	W					R
	
	// Frame number
	unsigned long frame;			//	W					R
};

#endif
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
#ifndef MATLAB_MEX_FILE
/* Global variables */

sem_t								sema;
struct rpitdd_data	data;
pthread_t           rpitdd_server_thread;

void* rpitdd_server_process_cmd( void* data_pointer )	{
	
	unsigned char				cmd = RPITDD_CMD_NOCMD;
  struct sched_param  my_param;
  int 	              my_policy;
  
  /* Change thread scheduling attributes: low priority scheduler */
  
  my_param.sched_priority = 0;
	my_policy = SCHED_IDLE;
	if ( pthread_setschedparam( pthread_self( ), my_policy, &my_param ) )
		fprintf( stderr, "rpitdd_server_process_cmd : unable to change thread scheduling parameters.\n" );

	if ( !pthread_getschedparam ( pthread_self( ), &my_policy, &my_param ) )  {
    if ( my_policy != SCHED_IDLE )  {
      fprintf( stderr, "rpitdd_server_process_cmd : unable to set SCHED_IDLE scheduling policy.\n" );
    }
  }
	else
		fprintf( stderr, "rpitdd_server_process_cmd : unable to get thread scheduling parameters.\n" );
  
  /* Internal check */
  
  if ( data_pointer )
    fprintf( stderr, "rpitdd_server_process_cmd: thread launched with unexpected parameter.\n" );
	
	/*
   *	Main loop.
   */ 
	
	do	{
		
		/* If device is started, update the data */
		
		if ( data.started )	{
			
			/* Request Polaris update */
			
			polaris_update( );
			
			/* Read Polaris data and update shared memory atomically */
			
			sem_wait( &sema );
			
			if (	pCommandAurora->m_dtHandleInformation[POLARIS_CUR_HANDLE].HandleInfo.bInitialized > 0 &&
            pCommandAurora->m_dtHandleInformation[POLARIS_CUR_HANDLE].szToolType[1] != '8' )	{
				
				// Update frame number
				data.frame = pCommandAurora->m_dtHandleInformation[POLARIS_CUR_HANDLE].Xfrms.ulFrameNumber;
				
				// If Frame is valid, update pose. If not, leave the previous pose.		
				if ( pCommandAurora->m_dtHandleInformation[POLARIS_CUR_HANDLE].Xfrms.ulFlags == TRANSFORM_VALID ) {
					
					data.x = pCommandAurora->m_dtHandleInformation[POLARIS_CUR_HANDLE].Xfrms.translation.x;
          data.y = pCommandAurora->m_dtHandleInformation[POLARIS_CUR_HANDLE].Xfrms.translation.y;
          data.z = pCommandAurora->m_dtHandleInformation[POLARIS_CUR_HANDLE].Xfrms.translation.z;
          data.q0 = pCommandAurora->m_dtHandleInformation[POLARIS_CUR_HANDLE].Xfrms.rotation.q0;
          data.qx = pCommandAurora->m_dtHandleInformation[POLARIS_CUR_HANDLE].Xfrms.rotation.qx;
          data.qy = pCommandAurora->m_dtHandleInformation[POLARIS_CUR_HANDLE].Xfrms.rotation.qy;
          data.qz = pCommandAurora->m_dtHandleInformation[POLARIS_CUR_HANDLE].Xfrms.rotation.qz;
          
          // Update status
          if ( pCommandAurora->m_dtHandleInformation[POLARIS_CUR_HANDLE].HandleInfo.bPartiallyOutOfVolume )
						data.status = RPITDD_POL_STATUS_PART;
					else if ( pCommandAurora->m_dtHandleInformation[POLARIS_CUR_HANDLE].HandleInfo.bOutOfVolume )
						data.status = RPITDD_POL_STATUS_OUT;
					else
						data.status = RPITDD_POL_STATUS_OK;
				}
				else
					data.status = RPITDD_POL_STATUS_INV;
			}
			
			sem_post( &sema );
			
		}
		
		/* Reading the command atomically */
		
		sem_wait( &sema );
		cmd = data.cmd;
		sem_post( &sema );
		
		/* Handling the command */

		switch( cmd )	{
			case RPITDD_CMD_NOCMD:
				break;
			
			case RPITDD_CMD_START:
				if ( polaris_start( ) == -1 )
					fprintf( stderr, "rpitdd_server: unable to start Polaris.\n" );
				else
				{
					sem_wait( &sema );
					data.started = 1;
					sem_post( &sema );
				}
        
				break;
			
			case RPITDD_CMD_STOP:
				if ( data.started )	{
					
					polaris_stop( );
					
					sem_wait( &sema );
					data.started = 0;
					sem_post( &sema );
				}
        
				break;
				
			case RPITDD_CMD_EXIT:
			
				fprintf( stderr, "rpitdd_server: exit command received.\n" );
				
				/* Stop device if started */
				
				if ( data.started )	{
					
					polaris_stop( );

					sem_wait( &sema );
					data.started = 0;
					sem_post( &sema );
				}
				
				break;
			
			default:
				fprintf( stderr, "rpitdd_server: unknown command received.\n" );
		}
	
		/* Write acknowledgement atomically */
    
    if ( cmd )  {
      sem_wait( &sema );
      data.cmd = RPITDD_CMD_NOCMD;
      sem_post( &sema );
    }
	}	while ( cmd != RPITDD_CMD_EXIT );

  return NULL;
}

int rpitdd_client_process_cmd( unsigned char cmd )	{
	unsigned char				ack;
	struct timespec 		ts1, ts2;
	
	/* Write a command atomically */
  
  sem_wait( &sema );
  data.cmd = cmd;
  sem_post( &sema );

  /* Wait for the acknowledgement with a timeout */
  
  clock_gettime( CLOCK_MONOTONIC, &ts1 );
  
  do	{
		
		clock_gettime( CLOCK_MONOTONIC, &ts2 );
		
		/* Read atomically the acknowledgement */
		
		sem_wait( &sema );
		ack = data.cmd;
		sem_post( &sema );
		
		/* Check for the timeout */
		
		if ( 	( ts2.tv_sec - ts1.tv_sec ) * 1000 + 
					( ts2.tv_nsec - ts1.tv_nsec ) / 1000000
					> RPITDD_ACK_TIMEOUT_MS )	{
			fprintf( stderr, "rpitdd_client_process_cmd: command acknowledge timeout.\n" ); 
			return -2;
		}
    
    /* Passive wait */
    
    usleep( 1000 );
    
	} while ( ack );

return 0;
}

void rpitdd_server_shutdown( void )	{
	
	/* Stop the device */
		
	if ( ( rpitdd_client_process_cmd( RPITDD_CMD_STOP ) ) )
    fprintf( stderr, "rpitdd_client: error processing command RPITDD_CMD_STOP.\n" );
  
  /* Stop the server */
  
  if ( ( rpitdd_client_process_cmd( RPITDD_CMD_EXIT ) ) )
		fprintf( stderr, "rpitdd_client: error processing command RPITDD_CMD_EXIT.\n" );
  
  /* Destroy IPC objects */
	
	sem_destroy( &sema );
}

int rpitdd_server_init( void )	{
	
	/*
	 * 	Initialize the named semaphore.
	 */
  
  if ( sem_init( &sema, 0, 1 ) )  {
    perror( "sem_init" );
    return -1;
  }
	
  /* Clear the data buffer */
  
  memset( &data, sizeof(  struct rpitdd_data ), 0 );
  
  /* Starting server processing loop thread */
  
  if ( pthread_create( &rpitdd_server_thread, NULL, rpitdd_server_process_cmd, NULL ) ) {
    fprintf( stderr, "rpitdd: unable to start command processing loop thread.\n" );
  }
  
  /* Start the Polaris */
  
  if ( rpitdd_client_process_cmd( RPITDD_CMD_START ) )
		fprintf( stderr, "rpitdd_client: error processing command RPITDD_CMD_START.\n" );

	return 0;
}

#endif
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void rpi_sfun_polaris_Outputs_wrapper(real_T *x,
                          real_T *y,
                          real_T *z,
                          real_T *q0,
                          real_T *qx,
                          real_T *qy,
                          real_T *qz,
                          real_T *state,
                          real_T *frame, 
                           const real_T  *rpi_Ts, const int_T p_width0)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
  #ifdef MATLAB_MEX_FILE

  x[0] = 0.0;
  y[0] = 0.0;
  z[0] = 0.0;
  q0[0] = 0.0;
  qx[0] = 0.0;
  qy[0] = 0.0;
  qz[0] = 0.0;
  state[0] = 0.0;
  frame[0] = 0.0;

  #else

  if ( p_width0 > 1 )	{
    fprintf( stderr, "** Multiple rates not allowed in this block **\n" );
    x[0] = 0.0;
    y[0] = 0.0;
    z[0] = 0.0;
    q0[0] = 0.0;
    qx[0] = 0.0;
    qy[0] = 0.0;
    qz[0] = 0.0;
    state[0] = 0.0;
    frame[0] = 0.0;
    return;
  }

  if ( *rpi_Ts < 0.001 )	{
    fprintf( stderr, "** Max sampling rate = 1000Hz **\n" );
    x[0] = 0.0;
    y[0] = 0.0;
    z[0] = 0.0;
    q0[0] = 0.0;
    qx[0] = 0.0;
    qy[0] = 0.0;
    qz[0] = 0.0;
    state[0] = 0.0;
    frame[0] = 0.0;
    return;
  }
  
  /* Refresh measurements */
  
  sem_wait( &sema );
  x[0] = data.x;
  y[0] = data.y;
  z[0] = data.z;
  q0[0] = data.q0;
  qx[0] = data.qx;
  qy[0] = data.qy;
  qz[0] = data.qz;
  state[0] = data.status;
  frame[0] = data.frame;
  sem_post( &sema );

  #endif
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
