/*
 * File: rpi_sfun_teensyshot.c
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand, 
 *   you must change it only in the area defined as:  
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text' 
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  ------------------------------------------------------------------------- 
 *
 * Created: Thu Jun 27 09:46:34 2019
 */

#define S_FUNCTION_LEVEL 2
#define S_FUNCTION_NAME rpi_sfun_teensyshot
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS            6
/* Input Port  0 */
#define IN_PORT_0_NAME        u1
#define INPUT_0_WIDTH         1
#define INPUT_DIMS_0_COL      1
#define INPUT_0_DTYPE         real_T
#define INPUT_0_COMPLEX       COMPLEX_NO
#define IN_0_FRAME_BASED      FRAME_NO
#define IN_0_BUS_BASED        0
#define IN_0_BUS_NAME         
#define IN_0_DIMS             1-D
#define INPUT_0_FEEDTHROUGH   1
#define IN_0_ISSIGNED         0
#define IN_0_WORDLENGTH       8
#define IN_0_FIXPOINTSCALING  1
#define IN_0_FRACTIONLENGTH   9
#define IN_0_BIAS             0
#define IN_0_SLOPE            0.125
/* Input Port  1 */
#define IN_PORT_1_NAME        u2
#define INPUT_1_WIDTH         1
#define INPUT_DIMS_1_COL      1
#define INPUT_1_DTYPE         real_T
#define INPUT_1_COMPLEX       COMPLEX_NO
#define IN_1_FRAME_BASED      FRAME_NO
#define IN_1_BUS_BASED        0
#define IN_1_BUS_NAME         
#define IN_1_DIMS             1-D
#define INPUT_1_FEEDTHROUGH   1
#define IN_1_ISSIGNED         0
#define IN_1_WORDLENGTH       8
#define IN_1_FIXPOINTSCALING  1
#define IN_1_FRACTIONLENGTH   9
#define IN_1_BIAS             0
#define IN_1_SLOPE            0.125
/* Input Port  2 */
#define IN_PORT_2_NAME        u3
#define INPUT_2_WIDTH         1
#define INPUT_DIMS_2_COL      1
#define INPUT_2_DTYPE         real_T
#define INPUT_2_COMPLEX       COMPLEX_NO
#define IN_2_FRAME_BASED      FRAME_NO
#define IN_2_BUS_BASED        0
#define IN_2_BUS_NAME         
#define IN_2_DIMS             1-D
#define INPUT_2_FEEDTHROUGH   1
#define IN_2_ISSIGNED         0
#define IN_2_WORDLENGTH       8
#define IN_2_FIXPOINTSCALING  1
#define IN_2_FRACTIONLENGTH   9
#define IN_2_BIAS             0
#define IN_2_SLOPE            0.125
/* Input Port  3 */
#define IN_PORT_3_NAME        u4
#define INPUT_3_WIDTH         1
#define INPUT_DIMS_3_COL      1
#define INPUT_3_DTYPE         real_T
#define INPUT_3_COMPLEX       COMPLEX_NO
#define IN_3_FRAME_BASED      FRAME_NO
#define IN_3_BUS_BASED        0
#define IN_3_BUS_NAME         
#define IN_3_DIMS             1-D
#define INPUT_3_FEEDTHROUGH   1
#define IN_3_ISSIGNED         0
#define IN_3_WORDLENGTH       8
#define IN_3_FIXPOINTSCALING  1
#define IN_3_FRACTIONLENGTH   9
#define IN_3_BIAS             0
#define IN_3_SLOPE            0.125
/* Input Port  4 */
#define IN_PORT_4_NAME        u5
#define INPUT_4_WIDTH         1
#define INPUT_DIMS_4_COL      1
#define INPUT_4_DTYPE         real_T
#define INPUT_4_COMPLEX       COMPLEX_NO
#define IN_4_FRAME_BASED      FRAME_NO
#define IN_4_BUS_BASED        0
#define IN_4_BUS_NAME         
#define IN_4_DIMS             1-D
#define INPUT_4_FEEDTHROUGH   1
#define IN_4_ISSIGNED         0
#define IN_4_WORDLENGTH       8
#define IN_4_FIXPOINTSCALING  1
#define IN_4_FRACTIONLENGTH   9
#define IN_4_BIAS             0
#define IN_4_SLOPE            0.125
/* Input Port  5 */
#define IN_PORT_5_NAME        u6
#define INPUT_5_WIDTH         1
#define INPUT_DIMS_5_COL      1
#define INPUT_5_DTYPE         real_T
#define INPUT_5_COMPLEX       COMPLEX_NO
#define IN_5_FRAME_BASED      FRAME_NO
#define IN_5_BUS_BASED        0
#define IN_5_BUS_NAME         
#define IN_5_DIMS             1-D
#define INPUT_5_FEEDTHROUGH   1
#define IN_5_ISSIGNED         0
#define IN_5_WORDLENGTH       8
#define IN_5_FIXPOINTSCALING  1
#define IN_5_FRACTIONLENGTH   9
#define IN_5_BIAS             0
#define IN_5_SLOPE            0.125

#define NUM_OUTPUTS           6
/* Output Port  0 */
#define OUT_PORT_0_NAME       y1
#define OUTPUT_0_WIDTH        6
#define OUTPUT_DIMS_0_COL     1
#define OUTPUT_0_DTYPE        real_T
#define OUTPUT_0_COMPLEX      COMPLEX_NO
#define OUT_0_FRAME_BASED     FRAME_NO
#define OUT_0_BUS_BASED       0
#define OUT_0_BUS_NAME        
#define OUT_0_DIMS            1-D
#define OUT_0_ISSIGNED        1
#define OUT_0_WORDLENGTH      8
#define OUT_0_FIXPOINTSCALING 1
#define OUT_0_FRACTIONLENGTH  3
#define OUT_0_BIAS            0
#define OUT_0_SLOPE           0.125
/* Output Port  1 */
#define OUT_PORT_1_NAME       y2
#define OUTPUT_1_WIDTH        6
#define OUTPUT_DIMS_1_COL     1
#define OUTPUT_1_DTYPE        real_T
#define OUTPUT_1_COMPLEX      COMPLEX_NO
#define OUT_1_FRAME_BASED     FRAME_NO
#define OUT_1_BUS_BASED       0
#define OUT_1_BUS_NAME        
#define OUT_1_DIMS            1-D
#define OUT_1_ISSIGNED        1
#define OUT_1_WORDLENGTH      8
#define OUT_1_FIXPOINTSCALING 1
#define OUT_1_FRACTIONLENGTH  3
#define OUT_1_BIAS            0
#define OUT_1_SLOPE           0.125
/* Output Port  2 */
#define OUT_PORT_2_NAME       y3
#define OUTPUT_2_WIDTH        6
#define OUTPUT_DIMS_2_COL     1
#define OUTPUT_2_DTYPE        real_T
#define OUTPUT_2_COMPLEX      COMPLEX_NO
#define OUT_2_FRAME_BASED     FRAME_NO
#define OUT_2_BUS_BASED       0
#define OUT_2_BUS_NAME        
#define OUT_2_DIMS            1-D
#define OUT_2_ISSIGNED        1
#define OUT_2_WORDLENGTH      8
#define OUT_2_FIXPOINTSCALING 1
#define OUT_2_FRACTIONLENGTH  3
#define OUT_2_BIAS            0
#define OUT_2_SLOPE           0.125
/* Output Port  3 */
#define OUT_PORT_3_NAME       y4
#define OUTPUT_3_WIDTH        6
#define OUTPUT_DIMS_3_COL     1
#define OUTPUT_3_DTYPE        real_T
#define OUTPUT_3_COMPLEX      COMPLEX_NO
#define OUT_3_FRAME_BASED     FRAME_NO
#define OUT_3_BUS_BASED       0
#define OUT_3_BUS_NAME        
#define OUT_3_DIMS            1-D
#define OUT_3_ISSIGNED        1
#define OUT_3_WORDLENGTH      8
#define OUT_3_FIXPOINTSCALING 1
#define OUT_3_FRACTIONLENGTH  3
#define OUT_3_BIAS            0
#define OUT_3_SLOPE           0.125
/* Output Port  4 */
#define OUT_PORT_4_NAME       y5
#define OUTPUT_4_WIDTH        6
#define OUTPUT_DIMS_4_COL     1
#define OUTPUT_4_DTYPE        real_T
#define OUTPUT_4_COMPLEX      COMPLEX_NO
#define OUT_4_FRAME_BASED     FRAME_NO
#define OUT_4_BUS_BASED       0
#define OUT_4_BUS_NAME        
#define OUT_4_DIMS            1-D
#define OUT_4_ISSIGNED        1
#define OUT_4_WORDLENGTH      8
#define OUT_4_FIXPOINTSCALING 1
#define OUT_4_FRACTIONLENGTH  3
#define OUT_4_BIAS            0
#define OUT_4_SLOPE           0.125
/* Output Port  5 */
#define OUT_PORT_5_NAME       y6
#define OUTPUT_5_WIDTH        6
#define OUTPUT_DIMS_5_COL     1
#define OUTPUT_5_DTYPE        real_T
#define OUTPUT_5_COMPLEX      COMPLEX_NO
#define OUT_5_FRAME_BASED     FRAME_NO
#define OUT_5_BUS_BASED       0
#define OUT_5_BUS_NAME        
#define OUT_5_DIMS            1-D
#define OUT_5_ISSIGNED        1
#define OUT_5_WORDLENGTH      8
#define OUT_5_FIXPOINTSCALING 1
#define OUT_5_FRACTIONLENGTH  3
#define OUT_5_BIAS            0
#define OUT_5_SLOPE           0.125

#define NPARAMS               26
/* Parameter 0 */
#define PARAMETER_0_NAME      rpi_Ts
#define PARAMETER_0_DTYPE     real_T
#define PARAMETER_0_COMPLEX   COMPLEX_NO
/* Parameter 1 */
#define PARAMETER_1_NAME      P1
#define PARAMETER_1_DTYPE     real_T
#define PARAMETER_1_COMPLEX   COMPLEX_NO
/* Parameter 2 */
#define PARAMETER_2_NAME      I1
#define PARAMETER_2_DTYPE     real_T
#define PARAMETER_2_COMPLEX   COMPLEX_NO
/* Parameter 3 */
#define PARAMETER_3_NAME      D1
#define PARAMETER_3_DTYPE     real_T
#define PARAMETER_3_COMPLEX   COMPLEX_NO
/* Parameter 4 */
#define PARAMETER_4_NAME      f1
#define PARAMETER_4_DTYPE     real_T
#define PARAMETER_4_COMPLEX   COMPLEX_NO
/* Parameter 5 */
#define PARAMETER_5_NAME      P2
#define PARAMETER_5_DTYPE     real_T
#define PARAMETER_5_COMPLEX   COMPLEX_NO
/* Parameter 6 */
#define PARAMETER_6_NAME      I2
#define PARAMETER_6_DTYPE     real_T
#define PARAMETER_6_COMPLEX   COMPLEX_NO
/* Parameter 7 */
#define PARAMETER_7_NAME      D2
#define PARAMETER_7_DTYPE     real_T
#define PARAMETER_7_COMPLEX   COMPLEX_NO
/* Parameter 8 */
#define PARAMETER_8_NAME      f2
#define PARAMETER_8_DTYPE     real_T
#define PARAMETER_8_COMPLEX   COMPLEX_NO
/* Parameter 9 */
#define PARAMETER_9_NAME      P3
#define PARAMETER_9_DTYPE     real_T
#define PARAMETER_9_COMPLEX   COMPLEX_NO
/* Parameter 10 */
#define PARAMETER_10_NAME      I3
#define PARAMETER_10_DTYPE     real_T
#define PARAMETER_10_COMPLEX   COMPLEX_NO
/* Parameter 11 */
#define PARAMETER_11_NAME      D3
#define PARAMETER_11_DTYPE     real_T
#define PARAMETER_11_COMPLEX   COMPLEX_NO
/* Parameter 12 */
#define PARAMETER_12_NAME      f3
#define PARAMETER_12_DTYPE     real_T
#define PARAMETER_12_COMPLEX   COMPLEX_NO
/* Parameter 13 */
#define PARAMETER_13_NAME      P4
#define PARAMETER_13_DTYPE     real_T
#define PARAMETER_13_COMPLEX   COMPLEX_NO
/* Parameter 14 */
#define PARAMETER_14_NAME      I4
#define PARAMETER_14_DTYPE     real_T
#define PARAMETER_14_COMPLEX   COMPLEX_NO
/* Parameter 15 */
#define PARAMETER_15_NAME      D4
#define PARAMETER_15_DTYPE     real_T
#define PARAMETER_15_COMPLEX   COMPLEX_NO
/* Parameter 16 */
#define PARAMETER_16_NAME      f4
#define PARAMETER_16_DTYPE     real_T
#define PARAMETER_16_COMPLEX   COMPLEX_NO
/* Parameter 17 */
#define PARAMETER_17_NAME      P5
#define PARAMETER_17_DTYPE     real_T
#define PARAMETER_17_COMPLEX   COMPLEX_NO
/* Parameter 18 */
#define PARAMETER_18_NAME      I5
#define PARAMETER_18_DTYPE     real_T
#define PARAMETER_18_COMPLEX   COMPLEX_NO
/* Parameter 19 */
#define PARAMETER_19_NAME      D5
#define PARAMETER_19_DTYPE     real_T
#define PARAMETER_19_COMPLEX   COMPLEX_NO
/* Parameter 20 */
#define PARAMETER_20_NAME      f5
#define PARAMETER_20_DTYPE     real_T
#define PARAMETER_20_COMPLEX   COMPLEX_NO
/* Parameter 21 */
#define PARAMETER_21_NAME      P6
#define PARAMETER_21_DTYPE     real_T
#define PARAMETER_21_COMPLEX   COMPLEX_NO
/* Parameter 22 */
#define PARAMETER_22_NAME      I6
#define PARAMETER_22_DTYPE     real_T
#define PARAMETER_22_COMPLEX   COMPLEX_NO
/* Parameter 23 */
#define PARAMETER_23_NAME      D6
#define PARAMETER_23_DTYPE     real_T
#define PARAMETER_23_COMPLEX   COMPLEX_NO
/* Parameter 24 */
#define PARAMETER_24_NAME      f6
#define PARAMETER_24_DTYPE     real_T
#define PARAMETER_24_COMPLEX   COMPLEX_NO
/* Parameter 25 */
#define PARAMETER_25_NAME      Port
#define PARAMETER_25_DTYPE     uint32_T
#define PARAMETER_25_COMPLEX   COMPLEX_NO

#define SAMPLE_TIME_0         rpi_Ts
#define NUM_DISC_STATES       0
#define DISC_STATES_IC        [0]
#define NUM_CONT_STATES       0
#define CONT_STATES_IC        [0]

#define SFUNWIZ_GENERATE_TLC  1
#define SOURCEFILES           "__SFB__"
#define PANELINDEX            8
#define USE_SIMSTRUCT         0
#define SHOW_COMPILE_STEPS    1
#define CREATE_DEBUG_MEXFILE  0
#define SAVE_CODE_ONLY        1
#define SFUNWIZ_REVISION      3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"

#define PARAM_DEF0(S) ssGetSFcnParam(S, 0)
#define PARAM_DEF1(S) ssGetSFcnParam(S, 1)
#define PARAM_DEF2(S) ssGetSFcnParam(S, 2)
#define PARAM_DEF3(S) ssGetSFcnParam(S, 3)
#define PARAM_DEF4(S) ssGetSFcnParam(S, 4)
#define PARAM_DEF5(S) ssGetSFcnParam(S, 5)
#define PARAM_DEF6(S) ssGetSFcnParam(S, 6)
#define PARAM_DEF7(S) ssGetSFcnParam(S, 7)
#define PARAM_DEF8(S) ssGetSFcnParam(S, 8)
#define PARAM_DEF9(S) ssGetSFcnParam(S, 9)
#define PARAM_DEF10(S) ssGetSFcnParam(S, 10)
#define PARAM_DEF11(S) ssGetSFcnParam(S, 11)
#define PARAM_DEF12(S) ssGetSFcnParam(S, 12)
#define PARAM_DEF13(S) ssGetSFcnParam(S, 13)
#define PARAM_DEF14(S) ssGetSFcnParam(S, 14)
#define PARAM_DEF15(S) ssGetSFcnParam(S, 15)
#define PARAM_DEF16(S) ssGetSFcnParam(S, 16)
#define PARAM_DEF17(S) ssGetSFcnParam(S, 17)
#define PARAM_DEF18(S) ssGetSFcnParam(S, 18)
#define PARAM_DEF19(S) ssGetSFcnParam(S, 19)
#define PARAM_DEF20(S) ssGetSFcnParam(S, 20)
#define PARAM_DEF21(S) ssGetSFcnParam(S, 21)
#define PARAM_DEF22(S) ssGetSFcnParam(S, 22)
#define PARAM_DEF23(S) ssGetSFcnParam(S, 23)
#define PARAM_DEF24(S) ssGetSFcnParam(S, 24)
#define PARAM_DEF25(S) ssGetSFcnParam(S, 25)

#define IS_PARAM_DOUBLE(pVal) (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsDouble(pVal))

#define IS_PARAM_UINT32(pVal) (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsUint32(pVal))

extern void rpi_sfun_teensyshot_Start_wrapper(const real_T *rpi_Ts, const int_T p_width0,
			const real_T *P1, const int_T p_width1,
			const real_T *I1, const int_T p_width2,
			const real_T *D1, const int_T p_width3,
			const real_T *f1, const int_T p_width4,
			const real_T *P2, const int_T p_width5,
			const real_T *I2, const int_T p_width6,
			const real_T *D2, const int_T p_width7,
			const real_T *f2, const int_T p_width8,
			const real_T *P3, const int_T p_width9,
			const real_T *I3, const int_T p_width10,
			const real_T *D3, const int_T p_width11,
			const real_T *f3, const int_T p_width12,
			const real_T *P4, const int_T p_width13,
			const real_T *I4, const int_T p_width14,
			const real_T *D4, const int_T p_width15,
			const real_T *f4, const int_T p_width16,
			const real_T *P5, const int_T p_width17,
			const real_T *I5, const int_T p_width18,
			const real_T *D5, const int_T p_width19,
			const real_T *f5, const int_T p_width20,
			const real_T *P6, const int_T p_width21,
			const real_T *I6, const int_T p_width22,
			const real_T *D6, const int_T p_width23,
			const real_T *f6, const int_T p_width24,
			const uint32_T *Port, const int_T p_width25);
extern void rpi_sfun_teensyshot_Outputs_wrapper(const real_T *u1,
			const real_T *u2,
			const real_T *u3,
			const real_T *u4,
			const real_T *u5,
			const real_T *u6,
			real_T *y1,
			real_T *y2,
			real_T *y3,
			real_T *y4,
			real_T *y5,
			real_T *y6,
			const real_T *rpi_Ts, const int_T p_width0,
			const real_T *P1, const int_T p_width1,
			const real_T *I1, const int_T p_width2,
			const real_T *D1, const int_T p_width3,
			const real_T *f1, const int_T p_width4,
			const real_T *P2, const int_T p_width5,
			const real_T *I2, const int_T p_width6,
			const real_T *D2, const int_T p_width7,
			const real_T *f2, const int_T p_width8,
			const real_T *P3, const int_T p_width9,
			const real_T *I3, const int_T p_width10,
			const real_T *D3, const int_T p_width11,
			const real_T *f3, const int_T p_width12,
			const real_T *P4, const int_T p_width13,
			const real_T *I4, const int_T p_width14,
			const real_T *D4, const int_T p_width15,
			const real_T *f4, const int_T p_width16,
			const real_T *P5, const int_T p_width17,
			const real_T *I5, const int_T p_width18,
			const real_T *D5, const int_T p_width19,
			const real_T *f5, const int_T p_width20,
			const real_T *P6, const int_T p_width21,
			const real_T *I6, const int_T p_width22,
			const real_T *D6, const int_T p_width23,
			const real_T *f6, const int_T p_width24,
			const uint32_T *Port, const int_T p_width25);
extern void rpi_sfun_teensyshot_Terminate_wrapper(const real_T *rpi_Ts, const int_T p_width0,
			const real_T *P1, const int_T p_width1,
			const real_T *I1, const int_T p_width2,
			const real_T *D1, const int_T p_width3,
			const real_T *f1, const int_T p_width4,
			const real_T *P2, const int_T p_width5,
			const real_T *I2, const int_T p_width6,
			const real_T *D2, const int_T p_width7,
			const real_T *f2, const int_T p_width8,
			const real_T *P3, const int_T p_width9,
			const real_T *I3, const int_T p_width10,
			const real_T *D3, const int_T p_width11,
			const real_T *f3, const int_T p_width12,
			const real_T *P4, const int_T p_width13,
			const real_T *I4, const int_T p_width14,
			const real_T *D4, const int_T p_width15,
			const real_T *f4, const int_T p_width16,
			const real_T *P5, const int_T p_width17,
			const real_T *I5, const int_T p_width18,
			const real_T *D5, const int_T p_width19,
			const real_T *f5, const int_T p_width20,
			const real_T *P6, const int_T p_width21,
			const real_T *I6, const int_T p_width22,
			const real_T *D6, const int_T p_width23,
			const real_T *f6, const int_T p_width24,
			const uint32_T *Port, const int_T p_width25);
/*====================*
 * S-function methods *
 *====================*/
#define MDL_CHECK_PARAMETERS
#if defined(MDL_CHECK_PARAMETERS) && defined(MATLAB_MEX_FILE)
/* Function: mdlCheckParameters =============================================
 * Abstract:
 *     Verify parameter definitions and types.
 */
static void mdlCheckParameters(SimStruct *S)
{
    int paramIndex  = 0;
    bool invalidParam = false;
    /* All parameters must match the S-function Builder Dialog */

    {
        const mxArray *pVal0 = ssGetSFcnParam(S, 0);
        if (!mxIsDouble(pVal0)) {
            ssSetErrorStatus(S, "Sample time parameter rpi_Ts must be of type double");
            return;
        }
    }

    {
        const mxArray *pVal0 = ssGetSFcnParam(S, 0);
        if (!IS_PARAM_DOUBLE(pVal0)) {
            invalidParam = true;
            paramIndex = 0;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal1 = ssGetSFcnParam(S, 1);
        if (!IS_PARAM_DOUBLE(pVal1)) {
            invalidParam = true;
            paramIndex = 1;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal2 = ssGetSFcnParam(S, 2);
        if (!IS_PARAM_DOUBLE(pVal2)) {
            invalidParam = true;
            paramIndex = 2;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal3 = ssGetSFcnParam(S, 3);
        if (!IS_PARAM_DOUBLE(pVal3)) {
            invalidParam = true;
            paramIndex = 3;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal4 = ssGetSFcnParam(S, 4);
        if (!IS_PARAM_DOUBLE(pVal4)) {
            invalidParam = true;
            paramIndex = 4;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal5 = ssGetSFcnParam(S, 5);
        if (!IS_PARAM_DOUBLE(pVal5)) {
            invalidParam = true;
            paramIndex = 5;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal6 = ssGetSFcnParam(S, 6);
        if (!IS_PARAM_DOUBLE(pVal6)) {
            invalidParam = true;
            paramIndex = 6;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal7 = ssGetSFcnParam(S, 7);
        if (!IS_PARAM_DOUBLE(pVal7)) {
            invalidParam = true;
            paramIndex = 7;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal8 = ssGetSFcnParam(S, 8);
        if (!IS_PARAM_DOUBLE(pVal8)) {
            invalidParam = true;
            paramIndex = 8;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal9 = ssGetSFcnParam(S, 9);
        if (!IS_PARAM_DOUBLE(pVal9)) {
            invalidParam = true;
            paramIndex = 9;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal10 = ssGetSFcnParam(S, 10);
        if (!IS_PARAM_DOUBLE(pVal10)) {
            invalidParam = true;
            paramIndex = 10;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal11 = ssGetSFcnParam(S, 11);
        if (!IS_PARAM_DOUBLE(pVal11)) {
            invalidParam = true;
            paramIndex = 11;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal12 = ssGetSFcnParam(S, 12);
        if (!IS_PARAM_DOUBLE(pVal12)) {
            invalidParam = true;
            paramIndex = 12;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal13 = ssGetSFcnParam(S, 13);
        if (!IS_PARAM_DOUBLE(pVal13)) {
            invalidParam = true;
            paramIndex = 13;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal14 = ssGetSFcnParam(S, 14);
        if (!IS_PARAM_DOUBLE(pVal14)) {
            invalidParam = true;
            paramIndex = 14;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal15 = ssGetSFcnParam(S, 15);
        if (!IS_PARAM_DOUBLE(pVal15)) {
            invalidParam = true;
            paramIndex = 15;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal16 = ssGetSFcnParam(S, 16);
        if (!IS_PARAM_DOUBLE(pVal16)) {
            invalidParam = true;
            paramIndex = 16;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal17 = ssGetSFcnParam(S, 17);
        if (!IS_PARAM_DOUBLE(pVal17)) {
            invalidParam = true;
            paramIndex = 17;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal18 = ssGetSFcnParam(S, 18);
        if (!IS_PARAM_DOUBLE(pVal18)) {
            invalidParam = true;
            paramIndex = 18;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal19 = ssGetSFcnParam(S, 19);
        if (!IS_PARAM_DOUBLE(pVal19)) {
            invalidParam = true;
            paramIndex = 19;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal20 = ssGetSFcnParam(S, 20);
        if (!IS_PARAM_DOUBLE(pVal20)) {
            invalidParam = true;
            paramIndex = 20;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal21 = ssGetSFcnParam(S, 21);
        if (!IS_PARAM_DOUBLE(pVal21)) {
            invalidParam = true;
            paramIndex = 21;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal22 = ssGetSFcnParam(S, 22);
        if (!IS_PARAM_DOUBLE(pVal22)) {
            invalidParam = true;
            paramIndex = 22;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal23 = ssGetSFcnParam(S, 23);
        if (!IS_PARAM_DOUBLE(pVal23)) {
            invalidParam = true;
            paramIndex = 23;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal24 = ssGetSFcnParam(S, 24);
        if (!IS_PARAM_DOUBLE(pVal24)) {
            invalidParam = true;
            paramIndex = 24;
            goto EXIT_POINT;
        }
    }

    {
        const mxArray *pVal25 = ssGetSFcnParam(S, 25);
        if (!IS_PARAM_UINT32(pVal25)) {
            invalidParam = true;
            paramIndex = 25;
            goto EXIT_POINT;
        }
    }


    EXIT_POINT:
    if (invalidParam) {
        char parameterErrorMsg[1024];
        sprintf(parameterErrorMsg, "The data type and or complexity of parameter %d does not match the "
                "information specified in the S-function Builder dialog. "
                "For non-double parameters you will need to cast them using int8, int16, "
                "int32, uint8, uint16, uint32 or boolean.", paramIndex + 1);
        ssSetErrorStatus(S, parameterErrorMsg);
    }
    return;
}
#endif /* MDL_CHECK_PARAMETERS */
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{

    DECL_AND_INIT_DIMSINFO(inputDimsInfo);
    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS); /* Number of expected parameters */
    #if defined(MATLAB_MEX_FILE)
    if (ssGetNumSFcnParams(S) == ssGetSFcnParamsCount(S)) {
        mdlCheckParameters(S);
        if (ssGetErrorStatus(S) != NULL) {
            return;
        }
    } else {
        return; /* Parameter mismatch will be reported by Simulink */
    }
    #endif

    ssSetArrayLayoutForCodeGen(S, SS_COLUMN_MAJOR);

    ssSetSimStateCompliance(S, USE_DEFAULT_SIM_STATE);

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);


    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;
    /* Input Port 0 */
    ssSetInputPortWidth(S, 0, INPUT_0_WIDTH);
    ssSetInputPortDataType(S, 0, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 0, 1); /*direct input signal access*/

    /* Input Port 1 */
    ssSetInputPortWidth(S, 1, INPUT_1_WIDTH);
    ssSetInputPortDataType(S, 1, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 1, INPUT_1_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 1, 1); /*direct input signal access*/

    /* Input Port 2 */
    ssSetInputPortWidth(S, 2, INPUT_2_WIDTH);
    ssSetInputPortDataType(S, 2, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 2, INPUT_2_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 2, 1); /*direct input signal access*/

    /* Input Port 3 */
    ssSetInputPortWidth(S, 3, INPUT_3_WIDTH);
    ssSetInputPortDataType(S, 3, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 3, INPUT_3_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 3, INPUT_3_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 3, 1); /*direct input signal access*/

    /* Input Port 4 */
    ssSetInputPortWidth(S, 4, INPUT_4_WIDTH);
    ssSetInputPortDataType(S, 4, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 4, INPUT_4_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 4, INPUT_4_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 4, 1); /*direct input signal access*/

    /* Input Port 5 */
    ssSetInputPortWidth(S, 5, INPUT_5_WIDTH);
    ssSetInputPortDataType(S, 5, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 5, INPUT_5_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 5, INPUT_5_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 5, 1); /*direct input signal access*/


    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    /* Output Port 0 */
    ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);
    /* Output Port 1 */
    ssSetOutputPortWidth(S, 1, OUTPUT_1_WIDTH);
    ssSetOutputPortDataType(S, 1, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);
    /* Output Port 2 */
    ssSetOutputPortWidth(S, 2, OUTPUT_2_WIDTH);
    ssSetOutputPortDataType(S, 2, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);
    /* Output Port 3 */
    ssSetOutputPortWidth(S, 3, OUTPUT_3_WIDTH);
    ssSetOutputPortDataType(S, 3, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 3, OUTPUT_3_COMPLEX);
    /* Output Port 4 */
    ssSetOutputPortWidth(S, 4, OUTPUT_4_WIDTH);
    ssSetOutputPortDataType(S, 4, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 4, OUTPUT_4_COMPLEX);
    /* Output Port 5 */
    ssSetOutputPortWidth(S, 5, OUTPUT_5_WIDTH);
    ssSetOutputPortDataType(S, 5, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 5, OUTPUT_5_COMPLEX);
    ssSetNumPWork(S, 0);

    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    ssSetSimulinkVersionGeneratedIn(S, "9.2");

    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                     SS_OPTION_USE_TLC_WITH_ACCELERATOR |
                     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, *mxGetPr(ssGetSFcnParam(S, 0)));
    ssSetModelReferenceSampleTimeDefaultInheritance(S);
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE
static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
    ssSetInputPortDataType(S, 0, SS_DOUBLE);
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_SET_WORK_WIDTHS
#if defined(MDL_SET_WORK_WIDTHS) && defined(MATLAB_MEX_FILE)

static void mdlSetWorkWidths(SimStruct *S)
{

    const char_T *rtParamNames[] = {"P1","P2","P3","P4","P5","P6","P7","P8","P9","P10","P11","P12","P13","P14","P15","P16","P17","P18","P19","P20","P21","P22","P23","P24","P25","P26"};
    ssRegAllTunableParamsAsRunTimeParams(S, rtParamNames);

}

#endif

#define MDL_START  /* Change to #undef to remove function */
#if defined(MDL_START)
/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
    const int_T   p_width0  = mxGetNumberOfElements(PARAM_DEF0(S));
    const int_T   p_width1  = mxGetNumberOfElements(PARAM_DEF1(S));
    const int_T   p_width2  = mxGetNumberOfElements(PARAM_DEF2(S));
    const int_T   p_width3  = mxGetNumberOfElements(PARAM_DEF3(S));
    const int_T   p_width4  = mxGetNumberOfElements(PARAM_DEF4(S));
    const int_T   p_width5  = mxGetNumberOfElements(PARAM_DEF5(S));
    const int_T   p_width6  = mxGetNumberOfElements(PARAM_DEF6(S));
    const int_T   p_width7  = mxGetNumberOfElements(PARAM_DEF7(S));
    const int_T   p_width8  = mxGetNumberOfElements(PARAM_DEF8(S));
    const int_T   p_width9  = mxGetNumberOfElements(PARAM_DEF9(S));
    const int_T   p_width10  = mxGetNumberOfElements(PARAM_DEF10(S));
    const int_T   p_width11  = mxGetNumberOfElements(PARAM_DEF11(S));
    const int_T   p_width12  = mxGetNumberOfElements(PARAM_DEF12(S));
    const int_T   p_width13  = mxGetNumberOfElements(PARAM_DEF13(S));
    const int_T   p_width14  = mxGetNumberOfElements(PARAM_DEF14(S));
    const int_T   p_width15  = mxGetNumberOfElements(PARAM_DEF15(S));
    const int_T   p_width16  = mxGetNumberOfElements(PARAM_DEF16(S));
    const int_T   p_width17  = mxGetNumberOfElements(PARAM_DEF17(S));
    const int_T   p_width18  = mxGetNumberOfElements(PARAM_DEF18(S));
    const int_T   p_width19  = mxGetNumberOfElements(PARAM_DEF19(S));
    const int_T   p_width20  = mxGetNumberOfElements(PARAM_DEF20(S));
    const int_T   p_width21  = mxGetNumberOfElements(PARAM_DEF21(S));
    const int_T   p_width22  = mxGetNumberOfElements(PARAM_DEF22(S));
    const int_T   p_width23  = mxGetNumberOfElements(PARAM_DEF23(S));
    const int_T   p_width24  = mxGetNumberOfElements(PARAM_DEF24(S));
    const int_T   p_width25  = mxGetNumberOfElements(PARAM_DEF25(S));
    const real_T *rpi_Ts = (const real_T *) mxGetData(PARAM_DEF0(S));
    const real_T *P1 = (const real_T *) mxGetData(PARAM_DEF1(S));
    const real_T *I1 = (const real_T *) mxGetData(PARAM_DEF2(S));
    const real_T *D1 = (const real_T *) mxGetData(PARAM_DEF3(S));
    const real_T *f1 = (const real_T *) mxGetData(PARAM_DEF4(S));
    const real_T *P2 = (const real_T *) mxGetData(PARAM_DEF5(S));
    const real_T *I2 = (const real_T *) mxGetData(PARAM_DEF6(S));
    const real_T *D2 = (const real_T *) mxGetData(PARAM_DEF7(S));
    const real_T *f2 = (const real_T *) mxGetData(PARAM_DEF8(S));
    const real_T *P3 = (const real_T *) mxGetData(PARAM_DEF9(S));
    const real_T *I3 = (const real_T *) mxGetData(PARAM_DEF10(S));
    const real_T *D3 = (const real_T *) mxGetData(PARAM_DEF11(S));
    const real_T *f3 = (const real_T *) mxGetData(PARAM_DEF12(S));
    const real_T *P4 = (const real_T *) mxGetData(PARAM_DEF13(S));
    const real_T *I4 = (const real_T *) mxGetData(PARAM_DEF14(S));
    const real_T *D4 = (const real_T *) mxGetData(PARAM_DEF15(S));
    const real_T *f4 = (const real_T *) mxGetData(PARAM_DEF16(S));
    const real_T *P5 = (const real_T *) mxGetData(PARAM_DEF17(S));
    const real_T *I5 = (const real_T *) mxGetData(PARAM_DEF18(S));
    const real_T *D5 = (const real_T *) mxGetData(PARAM_DEF19(S));
    const real_T *f5 = (const real_T *) mxGetData(PARAM_DEF20(S));
    const real_T *P6 = (const real_T *) mxGetData(PARAM_DEF21(S));
    const real_T *I6 = (const real_T *) mxGetData(PARAM_DEF22(S));
    const real_T *D6 = (const real_T *) mxGetData(PARAM_DEF23(S));
    const real_T *f6 = (const real_T *) mxGetData(PARAM_DEF24(S));
    const uint32_T *Port = (const uint32_T *) mxGetData(PARAM_DEF25(S));
    
    rpi_sfun_teensyshot_Start_wrapper(rpi_Ts, p_width0, P1, p_width1, I1, p_width2, D1, p_width3, f1, p_width4, P2, p_width5, I2, p_width6, D2, p_width7, f2, p_width8, P3, p_width9, I3, p_width10, D3, p_width11, f3, p_width12, P4, p_width13, I4, p_width14, D4, p_width15, f4, p_width16, P5, p_width17, I5, p_width18, D5, p_width19, f5, p_width20, P6, p_width21, I6, p_width22, D6, p_width23, f6, p_width24, Port, p_width25);
}
#endif /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
    const real_T *u1 = (real_T *) ssGetInputPortRealSignal(S, 0);
    const real_T *u2 = (real_T *) ssGetInputPortRealSignal(S, 1);
    const real_T *u3 = (real_T *) ssGetInputPortRealSignal(S, 2);
    const real_T *u4 = (real_T *) ssGetInputPortRealSignal(S, 3);
    const real_T *u5 = (real_T *) ssGetInputPortRealSignal(S, 4);
    const real_T *u6 = (real_T *) ssGetInputPortRealSignal(S, 5);
    real_T *y1 = (real_T *) ssGetOutputPortRealSignal(S, 0);
    real_T *y2 = (real_T *) ssGetOutputPortRealSignal(S, 1);
    real_T *y3 = (real_T *) ssGetOutputPortRealSignal(S, 2);
    real_T *y4 = (real_T *) ssGetOutputPortRealSignal(S, 3);
    real_T *y5 = (real_T *) ssGetOutputPortRealSignal(S, 4);
    real_T *y6 = (real_T *) ssGetOutputPortRealSignal(S, 5);
    const int_T   p_width0  = mxGetNumberOfElements(PARAM_DEF0(S));
    const int_T   p_width1  = mxGetNumberOfElements(PARAM_DEF1(S));
    const int_T   p_width2  = mxGetNumberOfElements(PARAM_DEF2(S));
    const int_T   p_width3  = mxGetNumberOfElements(PARAM_DEF3(S));
    const int_T   p_width4  = mxGetNumberOfElements(PARAM_DEF4(S));
    const int_T   p_width5  = mxGetNumberOfElements(PARAM_DEF5(S));
    const int_T   p_width6  = mxGetNumberOfElements(PARAM_DEF6(S));
    const int_T   p_width7  = mxGetNumberOfElements(PARAM_DEF7(S));
    const int_T   p_width8  = mxGetNumberOfElements(PARAM_DEF8(S));
    const int_T   p_width9  = mxGetNumberOfElements(PARAM_DEF9(S));
    const int_T   p_width10  = mxGetNumberOfElements(PARAM_DEF10(S));
    const int_T   p_width11  = mxGetNumberOfElements(PARAM_DEF11(S));
    const int_T   p_width12  = mxGetNumberOfElements(PARAM_DEF12(S));
    const int_T   p_width13  = mxGetNumberOfElements(PARAM_DEF13(S));
    const int_T   p_width14  = mxGetNumberOfElements(PARAM_DEF14(S));
    const int_T   p_width15  = mxGetNumberOfElements(PARAM_DEF15(S));
    const int_T   p_width16  = mxGetNumberOfElements(PARAM_DEF16(S));
    const int_T   p_width17  = mxGetNumberOfElements(PARAM_DEF17(S));
    const int_T   p_width18  = mxGetNumberOfElements(PARAM_DEF18(S));
    const int_T   p_width19  = mxGetNumberOfElements(PARAM_DEF19(S));
    const int_T   p_width20  = mxGetNumberOfElements(PARAM_DEF20(S));
    const int_T   p_width21  = mxGetNumberOfElements(PARAM_DEF21(S));
    const int_T   p_width22  = mxGetNumberOfElements(PARAM_DEF22(S));
    const int_T   p_width23  = mxGetNumberOfElements(PARAM_DEF23(S));
    const int_T   p_width24  = mxGetNumberOfElements(PARAM_DEF24(S));
    const int_T   p_width25  = mxGetNumberOfElements(PARAM_DEF25(S));
    const real_T *rpi_Ts = (const real_T *) mxGetData(PARAM_DEF0(S));
    const real_T *P1 = (const real_T *) mxGetData(PARAM_DEF1(S));
    const real_T *I1 = (const real_T *) mxGetData(PARAM_DEF2(S));
    const real_T *D1 = (const real_T *) mxGetData(PARAM_DEF3(S));
    const real_T *f1 = (const real_T *) mxGetData(PARAM_DEF4(S));
    const real_T *P2 = (const real_T *) mxGetData(PARAM_DEF5(S));
    const real_T *I2 = (const real_T *) mxGetData(PARAM_DEF6(S));
    const real_T *D2 = (const real_T *) mxGetData(PARAM_DEF7(S));
    const real_T *f2 = (const real_T *) mxGetData(PARAM_DEF8(S));
    const real_T *P3 = (const real_T *) mxGetData(PARAM_DEF9(S));
    const real_T *I3 = (const real_T *) mxGetData(PARAM_DEF10(S));
    const real_T *D3 = (const real_T *) mxGetData(PARAM_DEF11(S));
    const real_T *f3 = (const real_T *) mxGetData(PARAM_DEF12(S));
    const real_T *P4 = (const real_T *) mxGetData(PARAM_DEF13(S));
    const real_T *I4 = (const real_T *) mxGetData(PARAM_DEF14(S));
    const real_T *D4 = (const real_T *) mxGetData(PARAM_DEF15(S));
    const real_T *f4 = (const real_T *) mxGetData(PARAM_DEF16(S));
    const real_T *P5 = (const real_T *) mxGetData(PARAM_DEF17(S));
    const real_T *I5 = (const real_T *) mxGetData(PARAM_DEF18(S));
    const real_T *D5 = (const real_T *) mxGetData(PARAM_DEF19(S));
    const real_T *f5 = (const real_T *) mxGetData(PARAM_DEF20(S));
    const real_T *P6 = (const real_T *) mxGetData(PARAM_DEF21(S));
    const real_T *I6 = (const real_T *) mxGetData(PARAM_DEF22(S));
    const real_T *D6 = (const real_T *) mxGetData(PARAM_DEF23(S));
    const real_T *f6 = (const real_T *) mxGetData(PARAM_DEF24(S));
    const uint32_T *Port = (const uint32_T *) mxGetData(PARAM_DEF25(S));
    
    rpi_sfun_teensyshot_Outputs_wrapper(u1, u2, u3, u4, u5, u6, y1, y2, y3, y4, y5, y6, rpi_Ts, p_width0, P1, p_width1, I1, p_width2, D1, p_width3, f1, p_width4, P2, p_width5, I2, p_width6, D2, p_width7, f2, p_width8, P3, p_width9, I3, p_width10, D3, p_width11, f3, p_width12, P4, p_width13, I4, p_width14, D4, p_width15, f4, p_width16, P5, p_width17, I5, p_width18, D5, p_width19, f5, p_width20, P6, p_width21, I6, p_width22, D6, p_width23, f6, p_width24, Port, p_width25);

}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
    const int_T   p_width0  = mxGetNumberOfElements(PARAM_DEF0(S));
    const int_T   p_width1  = mxGetNumberOfElements(PARAM_DEF1(S));
    const int_T   p_width2  = mxGetNumberOfElements(PARAM_DEF2(S));
    const int_T   p_width3  = mxGetNumberOfElements(PARAM_DEF3(S));
    const int_T   p_width4  = mxGetNumberOfElements(PARAM_DEF4(S));
    const int_T   p_width5  = mxGetNumberOfElements(PARAM_DEF5(S));
    const int_T   p_width6  = mxGetNumberOfElements(PARAM_DEF6(S));
    const int_T   p_width7  = mxGetNumberOfElements(PARAM_DEF7(S));
    const int_T   p_width8  = mxGetNumberOfElements(PARAM_DEF8(S));
    const int_T   p_width9  = mxGetNumberOfElements(PARAM_DEF9(S));
    const int_T   p_width10  = mxGetNumberOfElements(PARAM_DEF10(S));
    const int_T   p_width11  = mxGetNumberOfElements(PARAM_DEF11(S));
    const int_T   p_width12  = mxGetNumberOfElements(PARAM_DEF12(S));
    const int_T   p_width13  = mxGetNumberOfElements(PARAM_DEF13(S));
    const int_T   p_width14  = mxGetNumberOfElements(PARAM_DEF14(S));
    const int_T   p_width15  = mxGetNumberOfElements(PARAM_DEF15(S));
    const int_T   p_width16  = mxGetNumberOfElements(PARAM_DEF16(S));
    const int_T   p_width17  = mxGetNumberOfElements(PARAM_DEF17(S));
    const int_T   p_width18  = mxGetNumberOfElements(PARAM_DEF18(S));
    const int_T   p_width19  = mxGetNumberOfElements(PARAM_DEF19(S));
    const int_T   p_width20  = mxGetNumberOfElements(PARAM_DEF20(S));
    const int_T   p_width21  = mxGetNumberOfElements(PARAM_DEF21(S));
    const int_T   p_width22  = mxGetNumberOfElements(PARAM_DEF22(S));
    const int_T   p_width23  = mxGetNumberOfElements(PARAM_DEF23(S));
    const int_T   p_width24  = mxGetNumberOfElements(PARAM_DEF24(S));
    const int_T   p_width25  = mxGetNumberOfElements(PARAM_DEF25(S));
    const real_T *rpi_Ts = (const real_T *) mxGetData(PARAM_DEF0(S));
    const real_T *P1 = (const real_T *) mxGetData(PARAM_DEF1(S));
    const real_T *I1 = (const real_T *) mxGetData(PARAM_DEF2(S));
    const real_T *D1 = (const real_T *) mxGetData(PARAM_DEF3(S));
    const real_T *f1 = (const real_T *) mxGetData(PARAM_DEF4(S));
    const real_T *P2 = (const real_T *) mxGetData(PARAM_DEF5(S));
    const real_T *I2 = (const real_T *) mxGetData(PARAM_DEF6(S));
    const real_T *D2 = (const real_T *) mxGetData(PARAM_DEF7(S));
    const real_T *f2 = (const real_T *) mxGetData(PARAM_DEF8(S));
    const real_T *P3 = (const real_T *) mxGetData(PARAM_DEF9(S));
    const real_T *I3 = (const real_T *) mxGetData(PARAM_DEF10(S));
    const real_T *D3 = (const real_T *) mxGetData(PARAM_DEF11(S));
    const real_T *f3 = (const real_T *) mxGetData(PARAM_DEF12(S));
    const real_T *P4 = (const real_T *) mxGetData(PARAM_DEF13(S));
    const real_T *I4 = (const real_T *) mxGetData(PARAM_DEF14(S));
    const real_T *D4 = (const real_T *) mxGetData(PARAM_DEF15(S));
    const real_T *f4 = (const real_T *) mxGetData(PARAM_DEF16(S));
    const real_T *P5 = (const real_T *) mxGetData(PARAM_DEF17(S));
    const real_T *I5 = (const real_T *) mxGetData(PARAM_DEF18(S));
    const real_T *D5 = (const real_T *) mxGetData(PARAM_DEF19(S));
    const real_T *f5 = (const real_T *) mxGetData(PARAM_DEF20(S));
    const real_T *P6 = (const real_T *) mxGetData(PARAM_DEF21(S));
    const real_T *I6 = (const real_T *) mxGetData(PARAM_DEF22(S));
    const real_T *D6 = (const real_T *) mxGetData(PARAM_DEF23(S));
    const real_T *f6 = (const real_T *) mxGetData(PARAM_DEF24(S));
    const uint32_T *Port = (const uint32_T *) mxGetData(PARAM_DEF25(S));
    
    rpi_sfun_teensyshot_Terminate_wrapper(rpi_Ts, p_width0, P1, p_width1, I1, p_width2, D1, p_width3, f1, p_width4, P2, p_width5, I2, p_width6, D2, p_width7, f2, p_width8, P3, p_width9, I3, p_width10, D3, p_width11, f3, p_width12, P4, p_width13, I4, p_width14, D4, p_width15, f4, p_width16, P5, p_width17, I5, p_width18, D5, p_width19, f5, p_width20, P6, p_width21, I6, p_width22, D6, p_width23, f6, p_width24, Port, p_width25);

}


#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif



